package mnj.mfg.model;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue May 03 13:35:13 PKT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class buyerLOVImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public buyerLOVImpl() {
    }

    /**
     * Returns the variable value for p_buyer.
     * @return variable value for p_buyer
     */
    public String getp_buyer() {
        return (String)ensureVariableManager().getVariableValue("p_buyer");
    }

    /**
     * Sets <code>value</code> for variable p_buyer.
     * @param value value to bind as p_buyer
     */
    public void setp_buyer(String value) {
        ensureVariableManager().setVariableValue("p_buyer", value);
    }
}
