package mnj.mfg.model;

import java.sql.CallableStatement;

import java.sql.SQLException;

import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;

import java.util.Map;

import javax.faces.application.FacesMessage;
import javax.faces.context.ExternalContext;
import javax.faces.context.FacesContext;

import javax.servlet.http.HttpSession;

import javax.swing.text.Style;

import mnj.mfg.model.common.MainAM;
import mnj.mfg.model.lov.CustomerLOVImpl;
import mnj.mfg.model.lov.FillBposVOImpl;
import mnj.mfg.model.lov.InvOrgVOImpl;
import mnj.mfg.model.lov.operatingUnitsVoImpl;
import mnj.mfg.model.lov.papulateSizeVoImpl;

import mnj.mfg.model.lov.similarPopSizeVOImpl;

import mnj.mfg.model.views.HeaderVOImpl;

import mnj.mfg.model.views.HeaderVORowImpl;
import mnj.mfg.model.views.MNJ_ISSUEREC_WASH_DEL_SIZE_VOImpl;
import mnj.mfg.model.views.MNJ_ISSUEREC_WASH_REC_SIZE_VOImpl;
import mnj.mfg.model.views.MNJ_ISSUEREC_WASH_REC_SIZE_VORowImpl;
import mnj.mfg.model.views.MNJ_ISSUE_REC_WASH_DEL_L_VOImpl;
import mnj.mfg.model.views.MNJ_ISSUE_REC_WASH_DEL_L_VORowImpl;

import mnj.mfg.model.views.MNJ_ISSUE_REC_WASH_REC_L_VOImpl;
import mnj.mfg.model.views.MNJ_ISSUE_REC_WASH_REC_L_VORowImpl;

import oracle.adf.share.ADFContext;

import oracle.jbo.JboException;
import oracle.jbo.Row;
import oracle.jbo.RowSet;
import oracle.jbo.RowSetIterator;
import oracle.jbo.ViewObject;
import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewLinkImpl;


import oracle.jbo.server.ViewObjectImpl;

import oracle.jdbc.OracleTypes;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon May 02 18:30:01 PKT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MainAMImpl extends ApplicationModuleImpl implements MainAM {
    /**
     * This is the default constructor (do not remove).
     */
    public static final int VARCHAR2 = OracleTypes.NUMBER;
    public static final int INTEGER = OracleTypes.INTEGER;

    public MainAMImpl() {
    }


    public void FillRollLines() {


        ViewObject populatevo = getpapulateSizeVo1();
        // populatevo.executeQuery();

        Row[] r = populatevo.getAllRowsInRange();
        System.out.println("Drop ------->" + r.length);
        for (Row row : r) {

            if (row.getAttribute("FlagSize") != null &&
                row.getAttribute("FlagSize").equals("Y")) {
                System.out.println("FlagSize --->" +
                                   row.getAttribute("FlagSize"));
                popSizeAll(row);
            }
        }
    }

    public void popSizeAll(Row poprow) {


        Row linerow = getRollLine();

        linerow.setAttribute("Attribute1", getPopulateValue(poprow, "Inseam"));
        linerow.setAttribute("SizeInseam",
                             getPopulateValue(poprow, "SizeVal"));
        linerow.setAttribute("Quantity", getPopulateValue(poprow, "BalanceQty"));

    } //end of populateLines

    public Row getRollLine() {

        ViewObject vo = getMNJ_ISSUEREC_WASH_DEL_SIZE_VO1();
        Row row = vo.createRow();
        vo.insertRow(row);
        row.setNewRowState(Row.STATUS_INITIALIZED);
        return row;
    } //end of createHeader

    public String getPopulateValue(Row r, String columnName) {

        String value = null;
        try {
            value = r.getAttribute(columnName).toString();
        } catch (Exception e) {
            ;
        }
        return value;
    }

    public void setRollwhereClause() {
        System.out.println("Wher clause style -->" + getstyle());

        ViewObject vo = getpapulateSizeVo1();
//        vo.setWhereClause("STYLE = '" + getstyle() + "' AND BPO_NO = '" +
//                          getBpo() + "'");
        
        
        /**added by arif 4 march 2021**/
        vo.setWhereClause("BPO_ID = '" +
                                 getBpo() + "'");
        
        vo.executeQuery();
    }

    public String getstyle() {

        ViewObject vo = getMNJ_ISSUE_REC_WASH_DEL_L_VO1();
        String cutNo = null;
        try {
            cutNo = vo.getCurrentRow().getAttribute("Attribute5").toString();
        } catch (Exception e) {
            // TODO: Add catch code
            e.printStackTrace();
        }

        return cutNo;

    }


    /**
     * Container's getter for papulateSizeVo1.
     * @return papulateSizeVo1
     */
    public papulateSizeVoImpl getpapulateSizeVo1() {
        return (papulateSizeVoImpl)findViewObject("papulateSizeVo1");
    }

    //////////////////////////SimilarPOPSize////////

    public void FillRollLines1() {
        System.out.println("Enter FillRollLines1 ------->");
        ViewObject populatevo = getsimilarPopSizeVO1();
        // populatevo.executeQuery();

        Row[] r = populatevo.getAllRowsInRange();
        System.out.println("Drop FillRollLines1 ------->" + r.length);
        for (Row row : r) {

            if (row.getAttribute("SFLAG") != null &&
                row.getAttribute("SFLAG").equals("Y")) {
                System.out.println("SFLAG --->" + row.getAttribute("SFLAG"));
                popSizeAll1(row);
            }
        }
    }

    public void setRollwhereClause1() {
        System.out.println("HEADER_ID = " + getHeader_id() + " AND STN = '" +
                           getStn() + "'");

        ViewObject vo = getsimilarPopSizeVO1();
        vo.setWhereClause("STN = '" + getStn() + "'");
        System.out.println("Where clause Style HEADER_ID -->" +
                           getHeader_id());
        vo.executeQuery();
    }

    public String getHeader_id() {

        ViewObject vo = getHeaderVO1();
        String cutNo1 = null;
        try {
            cutNo1 = vo.getCurrentRow().getAttribute("HeaderId").toString();
        } catch (Exception e) {
            // TODO: Add catch code
            e.printStackTrace();
        }

        return cutNo1;

    }

    public String getStn() {

        ViewObject vo = getMNJ_ISSUE_REC_WASH_REC_L_VO1();
        String cutNo1 = null;
        try {
            cutNo1 = vo.getCurrentRow().getAttribute("Attribute2").toString();
        } catch (Exception e) {
            // TODO: Add catch code
            e.printStackTrace();
        }

        return cutNo1;

    }


    public void popSizeAll1(Row poprow) {

        System.out.println("Drop popSizeAll1 ------->");
        Row linerow1 = getRollLin();
        linerow1.setAttribute("Attribute1",
                              getPopulateValue1(poprow, "Attribute1"));
        linerow1.setAttribute("SizeInseam",
                              getPopulateValue1(poprow, "SizeInseam"));
        linerow1.setAttribute("Quantity",
                              getPopulateValue1(poprow, "Quantity"));

        System.out.println("after Drop popSizeAll1 ------->" + linerow1);
    } //end of populateLines


    public Row getRollLin() {

        ViewObject vo = getMNJ_ISSUEREC_WASH_REC_SIZE_VO1();
        Row row = vo.createRow();
        vo.insertRow(row);
        row.setNewRowState(Row.STATUS_INITIALIZED);
        return row;
    } //end of createHeader

    public String getPopulateValue1(Row r, String columnName) {

        String value = null;
        try {
            value = r.getAttribute(columnName).toString();
        } catch (Exception e) {
            ;
        }
        return value;
    }

    ///////////////////////////////////////////////

    /**
     * Container's getter for similarPopSizeVO1.
     * @return similarPopSizeVO1
     */
    public similarPopSizeVOImpl getsimilarPopSizeVO1() {
        return (similarPopSizeVOImpl)findViewObject("similarPopSizeVO1");
    }

    //////////////////////

    public void selectAllLines(String flag) {

        System.out.println("ENTER AM select all line ---->");
        ViewObject populatevo = getpapulateSizeVo1();
        //populatevo.executeQuery();

        Row[] r = populatevo.getAllRowsInRange();

        for (Row row : r) {
            System.out.println("Loop select");
            row.setAttribute("FlagSize", flag);
            System.out.println("Get select ---->" + row.getAttribute("Flag"));

        }
    }

    public void selectAllLines1(String flag) {

        System.out.println("ENTER AM select all line 1 ---->");
        ViewObject populatevo = getsimilarPopSizeVO1();
        //populatevo.executeQuery();

        Row[] r = populatevo.getAllRowsInRange();

        for (Row row : r) {
            System.out.println("Loop select 1");
            row.setAttribute("SFLAG", flag);
            System.out.println("Get select 1---->" +
                               row.getAttribute("SFLAG"));

        }
    }
    ////////////////////FILL BPO///////////

    public void FillRollLinesBPO() {
        System.out.println("INTER FillRollLinesBPO ------->");

        ViewObject populatevo = getFillBposVO1();
        // populatevo.executeQuery();

        Row[] r = populatevo.getAllRowsInRange();
        System.out.println("Drop BPO ------->" + r.length);
        for (Row row : r) {

            if (row.getAttribute("FlagNew") != null &&
                row.getAttribute("FlagNew").equals("Y")) {
                System.out.println("FlagNew bpo --->" +
                                   row.getAttribute("FlagNew"));
                popBPOAll(row);
                //getDBTransaction().commit();
            }
        }
    }

    public void popBPOAll(Row poprow) {


        Row linerow = getRollBPO();

        /* linerow.setAttribute("Attribute1", getPopulateValue(poprow, "BpoNo"));
        linerow.setAttribute("Attribute2",
                             getPopulateValue(poprow, "StnNumber"));
        linerow.setAttribute("Attribute3", getPopulateValue(poprow, "Color"));
        linerow.setAttribute("Attribute4", getPopulateValue(poprow, "Season"));
        linerow.setAttribute("Attribute5", getPopulateValue(poprow, "Style"));
        linerow.setAttribute("Quantity", getPopulateValue(poprow, "Quantity"));
        linerow.setAttribute("ProductionType",
                             getPopulateValue(poprow, "ProductionType"));
        linerow.setAttribute("Attribute6", getPopulateValue(poprow, "Buyer"));
        linerow.setAttribute("Attribute7",
                             getPopulateValue(poprow, "WashUnwash"));*/
        // ViewObject popup = getFillBposVO1();
        // popup.executeQuery();
        
        /***change for restructuring  by arif 4 march 2021***/
        
        linerow.setAttribute("BpoId", getPopulateValue(poprow, "BpoId"));
                linerow.setAttribute("Quantity", getPopulateValue(poprow, "Quantity"));
                linerow.setAttribute("ProductionType",
                                     getPopulateValue(poprow, "ProductionType"));
         
        
        
        
        

    } //end of populateLines

    public Row getRollBPO() {

        ViewObject vo = getMNJ_ISSUE_REC_WASH_DEL_L_VO1();
        Row row = vo.createRow();
        vo.insertRow(row);
        row.setNewRowState(Row.STATUS_INITIALIZED);
        return row;
    } //end of createHeader

    public void setRollwhereClauseBPO() {
        System.out.println("Wher clause cut no -->" + getstyle());

        ViewObject vo = getFillBposVO1();
        vo.setWhereClause("STYLE = '" + getstyle() + "'");
        vo.executeQuery();
    }


    /**
     * Container's getter for CustomerLOV1.
     * @return CustomerLOV1
     */
    public CustomerLOVImpl getCustomerLOV1() {
        return (CustomerLOVImpl)findViewObject("CustomerLOV1");
    }

    public String getBpo() {
        String Result = null;
        ViewObject vo = getMNJ_ISSUE_REC_WASH_DEL_L_VO1();
        Result = vo.getCurrentRow().getAttribute("BpoId").toString();
        return Result;
    }

    public String getStnNumber() {
        String Result = null;
        ViewObject vo = getMNJ_ISSUE_REC_WASH_DEL_L_VO1();
        Result = vo.getCurrentRow().getAttribute("Attribute2").toString();
        return Result;
    }

    public String getColor() {
        String Result = null;
        ViewObject vo = getMNJ_ISSUE_REC_WASH_DEL_L_VO1();
        Result = vo.getCurrentRow().getAttribute("Attribute3").toString();
        return Result;
    }


    public String getIssueChallanNo() {


        String result = "0";
        String stmt = "BEGIN :1 := MFG_DELIVERY_CHALLAN_NO(); end;";

        CallableStatement cs =
            getDBTransaction().createCallableStatement(stmt, 1);
        try {
            cs.registerOutParameter(1, OracleTypes.VARCHAR);
            cs.execute();
            result = cs.getString(1);
            cs.close();

        } catch (Exception e) {
            result = "0";
        }
        return result;

    }


    public void setSessionValues(String orgId, String userId, String respId,
                                 String respAppl) {


        if (userId != null) {
            //String flag = getFlagValue(userId, respId);
            FacesContext fctx = FacesContext.getCurrentInstance();
            ExternalContext ectx = fctx.getExternalContext();
            HttpSession userSession = (HttpSession)ectx.getSession(false);
            //userSession.setAttribute("Flag", flag);
            userSession.setAttribute("userId", userId);
            userSession.setAttribute("orgId", orgId);
            userSession.setAttribute("respId", respId);
            userSession.setAttribute("respAppl", respAppl);
            userSession.setAttribute("unitName", getUnitName(orgId));
        }
    }


    public String getUnitName(String orgId) {

        ViewObject vo = getoperatingUnitsVo1();
        vo.setWhereClause("ORGANIZATION_ID = " + orgId);
        vo.executeQuery();
        String name = null;
        vo.first();

        try {
            name = vo.getCurrentRow().getAttribute("Name").toString();
        } catch (Exception e) {
            // TODO: Add catch code
            e.printStackTrace();
        }
        return name;

    }


    public void Populate(String ReceiptChallanNo ) {
           
         String receiptStyleName;
          String  receiptChallanNo ;
         String receiptSeason;
       
            ViewObject vo = getHeaderVO1();
            
           
            try {
                receiptChallanNo =
                        vo.getCurrentRow().getAttribute("ReceiptChallanNo").toString();
                
            } catch (Exception e) {
                // TODO: Add catch code
                e.printStackTrace();
                return;
            }
            
           
           
        try {
            receiptStyleName =vo.getCurrentRow().getAttribute("StyleNew").toString();
                  
                   // vo.getCurrentRow().getAttribute("StyleName").toString();
            
        } catch (Exception e) {
            // TODO: Add catch code
            e.printStackTrace();
            return;
        }
        
        try {
            receiptSeason =vo.getCurrentRow().getAttribute("SeasonNew").toString();
                    //vo.getCurrentRow().getAttribute("Season").toString();
            
        } catch (Exception e) {
            // TODO: Add catch code
            e.printStackTrace();
            return;
        }
               
        int b;
   
        ViewObject populatevo = getPop_VO1(); // Populate VO
        populatevo.setWhereClause("RECEIVE_NO = '"+receiptChallanNo+"' AND STYLE = '"+receiptStyleName+"' AND SEASON ='"+ receiptSeason +"'");
        
        populatevo.executeQuery();
      //  populatevo.first();
       
        int cntRec = populatevo.getRowCount();
        populatevo.first();
        if (cntRec != 0) {
            for (b = 1; b <= cntRec; b++) {

                String V_ReceiptChallanNo;


                try {
                    V_ReceiptChallanNo =
                            populatevo.getCurrentRow().getAttribute("IssuanceChallanNo").toString();
                } catch (NullPointerException e) {
                    V_ReceiptChallanNo = null;
                }

               

                ViewObject vo_Line =
                    getMNJ_ISSUE_REC_WASH_REC_L_VO1(); // Lines VO


                Row r = vo_Line.createRow();
                vo_Line.last();
                vo_Line.next();
                vo_Line.insertRow(r);
                r.setNewRowState(Row.STATUS_INITIALIZED);

                // ----------------------------------------- Receiving Tab Data -------------------------------------- //

                r.setAttribute("BpoId",
                               populatevo.getCurrentRow().getAttribute("BpoId"));
              //  r.setAttribute("Attribute2",
                               //populatevo.getCurrentRow().getAttribute("Stn"));
              //  r.setAttribute("Attribute3",
                              // populatevo.getCurrentRow().getAttribute("Color"));
                r.setAttribute("Attribute4",
                               populatevo.getCurrentRow().getAttribute("Quantity"));
                r.setAttribute("ProductionType",
                               populatevo.getCurrentRow().getAttribute("ProductionType"));
                r.setAttribute("WashType",
                               populatevo.getCurrentRow().getAttribute("WashType"));
                r.setAttribute("RecevingChallanNo",
                               getIssueChallanNo_Receiving());
                //getDBTransaction().commit();
                
                String currentStn = populatevo.getCurrentRow().getAttribute("BpoId").toString();
                
                // 
                Populate_Sizes(receiptChallanNo ,currentStn );
                
                
                populatevo.next();
            }

        }

        getDBTransaction().commit();

        ViewObject popup = getFillBposVO1();
        popup.executeQuery();


    } //populate Lines


    public void Populate_Sizes(  String receiptChallanNo ,  String currentStn) {
     
        int b;
        
        System.out.println(" in  Populate_Sizes method  "); 
        System.out.println("  receiptChallanNo   :"+ receiptChallanNo +"currentStn "+currentStn );
        
        ViewObject populatevo = getsimilarPopSizeVO1(); // Populate VO
       //old  populatevo.setWhereClause("RECEIVE_NO='"+ receiptChallanNo +"' AND STN='"+currentStn+"'" );
       populatevo.setWhereClause("RECEIVE_NO='"+ receiptChallanNo +"' AND BPO_ID='"+currentStn+"'" );
        populatevo.executeQuery();
       // populatevo.first();
      
        int cntRec = populatevo.getRowCount();
        populatevo.first();
        if (cntRec != 0) {
            for (b = 1; b <= cntRec; b++) {

                String Stn;


                try {
                    Stn = populatevo.getCurrentRow().getAttribute("Stn").toString();
                } catch (NullPointerException e) {
                    Stn = null;
                }


                ViewObject vo_Line =
                    getMNJ_ISSUEREC_WASH_REC_SIZE_VO1(); // Lines VO


                Row r = vo_Line.createRow();
                vo_Line.last();
                vo_Line.next();
                vo_Line.insertRow(r);
                r.setNewRowState(Row.STATUS_INITIALIZED);

                // ----------------------------------------- Receiving Tab Data -------------------------------------- //

                r.setAttribute("Attribute1",
                               populatevo.getCurrentRow().getAttribute("Attribute1"));
                r.setAttribute("SizeInseam",
                               populatevo.getCurrentRow().getAttribute("SizeInseam"));
                r.setAttribute("Quantity",
                               populatevo.getCurrentRow().getAttribute("Quantity"));
                populatevo.next();
            }

        }

//      //  getDBTransaction().commit();

    } //populate Lines

    public void createLines() {
        ViewObject vo_Line4 = getHeaderVO1(); // Lines VO


        Row row = vo_Line4.createRow();
        vo_Line4.last();
        vo_Line4.next();
        vo_Line4.insertRow(row);
        row.setNewRowState(Row.STATUS_INITIALIZED);

        getDBTransaction().commit();
    }

    public String getIssueChallanNo_Receiving() {


        String result = "0";
        String stmt = "BEGIN :1 := MNJ_ISSUANCE_CHALLAN_NO_REC(); end;";

        CallableStatement cs =
            getDBTransaction().createCallableStatement(stmt, 1);
        try {
            cs.registerOutParameter(1, OracleTypes.VARCHAR);
            cs.execute();
            result = cs.getString(1);
            cs.close();

        } catch (Exception e) {
            result = "0";
        }
        return result;

    }

    public void save() {
        getDBTransaction().commit();
        //added by arif 4 march 2021
        ViewObject voc = getMNJ_ISSUE_REC_WASH_DEL_L_VO1();
        voc.clearCache();
        voc.executeQuery();
//        ViewObject popup = getFillBposVO1();
//        popup.executeQuery();
        check_rec_qty();
        Delivery_Qty_Check();
    }

    public void Quantity_Match_Check() {

        getDBTransaction().commit();
        ViewObject voc = getMNJ_ISSUE_REC_WASH_DEL_L_VO1();
        if (voc.getRowCount() != 0) {

            Double Line_Qty = 0.0;
            Double Detail_Qty = 0.0;

            String HeaderId = null;
            System.out.println("In method Quantity_Match_Check.....");


            try {
                ViewObject vo = getMNJ_ISSUE_REC_WASH_DEL_L_VO1();
                MNJ_ISSUE_REC_WASH_DEL_L_VORowImpl HeaderRow =
                    (MNJ_ISSUE_REC_WASH_DEL_L_VORowImpl)vo.getCurrentRow();

                try {
                    HeaderId = HeaderRow.getLineId().toString();
                } catch (Exception e) {
                    // TODO: Add catch code
                    HeaderId = null;
                    e.printStackTrace();
                }

                try {
                    Line_Qty =
                            Double.parseDouble(HeaderRow.getQuantity().toString());
                } catch (NullPointerException e) {
                    Line_Qty = 0.0;
                }

                System.out.println("Sum of Line Qty is.... " + Line_Qty);


                ViewObject voLineCount =
                    createViewObjectFromQueryStmt("voLineCountC",
                                                  "select sum(Quantity)Qty from MNJ_ISSUEREC_WASH_DEL_SIZE\n" +
                        "where line_id =" + "" + HeaderId);
                voLineCount.first();

                System.out.println("Query of Run time Query is...." +
                                   voLineCount.getQuery());

                Detail_Qty =
                        Double.parseDouble(voLineCount.getCurrentRow().getAttribute(0).toString());

                System.out.println("Sum of Detail Qty is... " + Detail_Qty);

                voLineCount.remove();


                if (Detail_Qty > Line_Qty) {
                    FacesContext context = FacesContext.getCurrentInstance();
                    FacesMessage message =
                        new FacesMessage(FacesMessage.SEVERITY_ERROR,
                                         "Delivery Size Quantity should not be greater than Delivery Quantity...",
                                         "");
                    //new FacesMessage("Delivery Size Quantity should not be greater than Delivery Quantity...");
                    context.addMessage(null, message);
                } else {
                    FacesContext context = FacesContext.getCurrentInstance();
                    FacesMessage message = new FacesMessage("Record Saved...");
                    context.addMessage(null, message);
                }
            } catch (Exception e) {
                // TODO: Add catch code

                e.printStackTrace();
            }

            getDBTransaction().commit();
        } else {
            System.out.println("Line Count is 0....");
        }
    }


    public void Detail_Delete_Check() {

        getDBTransaction().commit();
        String BPO = null;
        String STN = null;
        String BuyerId = null;
        String Style = null;
        String Season = null;
        String Color = null;
        String LineId = null;
        String HeaderId = null;
        System.out.println("In method Detail_Delete_Check.....");


        try {
            ViewObject vo = getMNJ_ISSUE_REC_WASH_REC_L_VO1();
            MNJ_ISSUE_REC_WASH_REC_L_VORowImpl HeaderRow =
                (MNJ_ISSUE_REC_WASH_REC_L_VORowImpl)vo.getCurrentRow();

            try {
                HeaderId = HeaderRow.getHeaderId().toString();
            } catch (Exception e) {
                // TODO: Add catch code
                HeaderId = null;
                e.printStackTrace();
            }

            try {
                LineId = HeaderRow.getLineId().toString();
            } catch (Exception e) {
                // TODO: Add catch code
                LineId = null;
                e.printStackTrace();
            }


            try {
                BPO = HeaderRow.getAttribute1().toString();
            } catch (NullPointerException e) {
                BPO = null;
            }

            System.out.println("BPO is.... " + BPO);

            try {
                STN = HeaderRow.getAttribute2().toString();
            } catch (NullPointerException e) {
                STN = null;
            }
            System.out.println("STN is.... " + STN);

            try {
                Color = HeaderRow.getAttribute3().toString();
            } catch (NullPointerException e) {
                Color = null;
            }
            System.out.println("Color is.... " + Color);

            ViewObject voLineBPO =
                createViewObjectFromQueryStmt("voLineBPOC", "select distinct (select hca.CUST_ACCOUNT_ID \n" +
                    "                       from hz_parties hp, hz_cust_accounts hca,ar_customers ac \n" +
                    "                         where hp.party_id = hca.party_id\n" + 
                    "                    AND hca.cust_account_id = ac.customer_id\n" + 
                    "                    AND hp.known_as IS NOT NULL\n" + 
                    "                    AND ac.status = 'A'\n" + 
                    "                    AND ac.customer_name_phonetic = 'M'\n" +
                    "                and hp.KNOWN_AS = h.attribute5) Buyer_id," +
                    "h.style_name ,h.season " +
                    "from MNJ_MFG_ISSUE_REC_WASH_H h\n" +
                    "                where header_id =" + "" + HeaderId);
            voLineBPO.first();

            System.out.println("Query of Run time Query is...." +
                               voLineBPO.getQuery());

            BuyerId = voLineBPO.getCurrentRow().getAttribute(0).toString();
            Style = voLineBPO.getCurrentRow().getAttribute(1).toString();
            Season = voLineBPO.getCurrentRow().getAttribute(2).toString();

            System.out.println("Parameters are is... " + BuyerId + Style +
                               Season);

            voLineBPO.remove();

            if (CheckBPO(BuyerId, Style, Season, BPO, STN, Color) == 1) {
                FacesContext context = FacesContext.getCurrentInstance();
                FacesMessage message =
                    new FacesMessage(FacesMessage.SEVERITY_ERROR,
                                     "Can not delete record as data exist in Delivery Tab....",
                                     "");
                //new FacesMessage("Delivery Size Quantity should not be greater than Delivery Quantity...");
                context.addMessage(null, message);
            } else {


                System.out.println("Line Id is ......" + LineId);
                Integer PHeaderId = Integer.parseInt(LineId);
                CallableStatement plSqlBlock = null;
                String Statement =
                    "BEGIN DELETE FROM MNJ_ISSUE_REC_WASH_REC_L WHERE LINE_ID = " +
                    PHeaderId + ";" + "COMMIT; END;";
                plSqlBlock =
                        getDBTransaction().createCallableStatement(Statement,
                                                                   0);
                try {
                    plSqlBlock.execute();
                    vo.executeQuery();

                } catch (SQLException e) {
                    e.printStackTrace();
                }


                FacesContext context = FacesContext.getCurrentInstance();
                FacesMessage message = new FacesMessage("Record Deleted...");
                context.addMessage(null, message);
            }


        } catch (Exception e) {
            // TODO: Add catch code

            e.printStackTrace();
        }


        getDBTransaction().commit();

    }

    public void ReceiveLines_Delete_Check() {

        getDBTransaction().commit();

        String ReceiptChallanNo = null;
        String HeaderId = null;
        System.out.println("In method Detail_Delete_Check.....");


        try {
            ViewObject vo = getHeaderVO1();
            HeaderVORowImpl HeaderRow = (HeaderVORowImpl)vo.getCurrentRow();

            try {
                HeaderId = HeaderRow.getHeaderId().toString();
            } catch (Exception e) {
                // TODO: Add catch code
                HeaderId = null;
                e.printStackTrace();
            }


            try {
                ReceiptChallanNo = HeaderRow.getReceiptChallanNo().toString();
            } catch (NullPointerException e) {
                ReceiptChallanNo = null;
            }

            System.out.println("ReceiptChallanNo is.... " + ReceiptChallanNo);


            if (CheckReceiptChallanNo(ReceiptChallanNo) == 1) {
                FacesContext context = FacesContext.getCurrentInstance();
                FacesMessage message =
                    new FacesMessage(FacesMessage.SEVERITY_ERROR,
                                     "Can not delete record as data exist on prior forms....",
                                     "");
                //new FacesMessage("Delivery Size Quantity should not be greater than Delivery Quantity...");
                context.addMessage(null, message);
            } else {


                System.out.println("Header Id is ......" + HeaderId);
                Integer PHeaderId = Integer.parseInt(HeaderId);
                CallableStatement plSqlBlock = null;
                String Statement =
                    "BEGIN DELETE FROM MNJ_MFG_ISSUE_REC_WASH_H WHERE HEADER_ID = " +
                    PHeaderId + ";" + "COMMIT; END;";
                plSqlBlock =
                        getDBTransaction().createCallableStatement(Statement,
                                                                   0);
                try {
                    plSqlBlock.execute();
                    vo.executeQuery();

                } catch (SQLException e) {
                    e.printStackTrace();
                }


                FacesContext context = FacesContext.getCurrentInstance();
                FacesMessage message = new FacesMessage("Record Deleted...");
                context.addMessage(null, message);
            }


        } catch (Exception e) {
            // TODO: Add catch code

            e.printStackTrace();
        }


        getDBTransaction().commit();

    }

    protected Object callStoredFunction(int sqlReturnType, String stmt,
                                        Object[] bindVars) {
        CallableStatement st = null;
        try {
            // 1. Create a JDBC CallabledStatement
            st =
 getDBTransaction().createCallableStatement("begin ? := " + stmt + ";end;", 0);
            // 2. Register the first bind variable for the return value
            st.registerOutParameter(1, sqlReturnType);
            if (bindVars != null) {
                // 3. Loop over values for the bind variables passed in, if any
                for (int z = 0; z < bindVars.length; z++) {
                    // 4. Set the value of user-supplied bind vars in the stmt
                    st.setObject(z + 2, bindVars[z]);
                }
            }
            // 5. Set the value of user-supplied bind vars in the stmt
            st.executeUpdate();
            // 6. Return the value of the first bind variable
            return st.getObject(1);

        } catch (SQLException e) {
            throw new JboException(e);
        } finally {
            if (st != null) {
                try {
                    // 7. Close the statement
                    st.close();
                } catch (SQLException e) {
                    ;
                }
            }
        }

    }

    public int CheckBPO(String BuyerId, String Style, String Season,
                        String BPO, String STN, String Color) {

        Map sessionScope = ADFContext.getCurrent().getSessionScope();

        String orgId = (String)sessionScope.get("orgId");
        System.out.println("Org ID is...." + orgId);

        int count = 0;
        count =
                (Integer)callStoredFunction(INTEGER, "mnj_washing_delete_validation.check_bpo(?, ?, ?, ?, ?,?)",
                                            new Object[] { BuyerId, Style,
                                                           Season, BPO, STN,
                                                           Color });

        return count;
    }

    public int CheckReceiptChallanNo(String ReceiptChallanNo) {

        Map sessionScope = ADFContext.getCurrent().getSessionScope();

        String orgId = (String)sessionScope.get("orgId");
        System.out.println("Org ID is...." + orgId);

        int count = 0;
        count =
                (Integer)callStoredFunction(INTEGER, "mnj_washing_delete_validation.check_RECEIPT_CHALLAN_NO(?, ?)",
                                            new Object[] { Integer.parseInt(orgId),
                                                           ReceiptChallanNo });

        return count;
    }


    public void Delivery_Qty_Check() {

        Double TotalQuantity_DD = 0.00;
        Double Quantity_DD = 0.00;

        Double Quantity_DL = 0.0;

        getDBTransaction().commit();

        System.out.println("In Tot_ProductionQtyCalc method.... ");

        ViewObject lvo = this.getMNJ_ISSUE_REC_WASH_DEL_L_VO1();
        RowSetIterator lvoit = lvo.createRowSetIterator("lvoit");

        while (lvoit.hasNext()) {

            Row linesNext = lvoit.next();
            String LineId = null;
            Quantity_DL = 0.00;
            TotalQuantity_DD = 0.00;
            Quantity_DD = 0.00;

            try {
                LineId = linesNext.getAttribute("LineId").toString();
            } catch (Exception e) {
                ;
            }

            try {
                Quantity_DL =
                        Double.parseDouble(linesNext.getAttribute("Quantity").toString());
                System.out.println("Quantity at Line is... " + Quantity_DL);
            } catch (Exception ee) {
                Quantity_DL = 0.0;
                System.out.println("Exception Quantity_DL");
            }

            RowSet DetailVO1it =
                (RowSet)linesNext.getAttribute("MNJ_ISSUEREC_WASH_DEL_SIZE_VO");

            while (DetailVO1it.hasNext()) {

                Row detailNext = DetailVO1it.next();

                String Detail_Id = null;
                try {
                    Detail_Id =
                            detailNext.getAttribute("SizeDetail").toString();
                } catch (Exception e) {
                    ;
                }

                try {
                    Quantity_DD =
                            Double.parseDouble(detailNext.getAttribute("Quantity").toString());
                    System.out.println("Quantity_DD at Detail is... " +
                                       Quantity_DD);
                } catch (Exception ee) {
                    Quantity_DD = 0.0;
                    System.out.println("Exception Quantity_DD");
                }

                TotalQuantity_DD = TotalQuantity_DD + Quantity_DD;

                System.out.println("Total of Detail is ...." +
                                   TotalQuantity_DD);
            }
            int count = DetailVO1it.getRowCount();
            System.out.println("Row Count of Detail is...." + count);
            DetailVO1it.closeRowSetIterator();
            if (count != 0) {
                linesNext.setAttribute("Quantity", TotalQuantity_DD);
            } else {
                System.out.println("Size Count is 0");
            }
        }
        lvoit.closeRowSetIterator();
        System.out.println("Save.....");

        this.getDBTransaction().commit();
    }

    public void Sizes_Delete_Check() {

        getDBTransaction().commit();
        String BPO = null;
        String STN = null;
        String BuyerId = null;
        String Style = null;
        String Season = null;
        String Color = null;
        String LineId = null;
        String DetailId = null;
        String HeaderId = null;
        System.out.println("In method Detail_Delete_Check.....");


        try {
            ViewObject vo = getMNJ_ISSUE_REC_WASH_REC_L_VO1();
            MNJ_ISSUE_REC_WASH_REC_L_VORowImpl HeaderRow =
                (MNJ_ISSUE_REC_WASH_REC_L_VORowImpl)vo.getCurrentRow();


            ViewObject vold = getMNJ_ISSUEREC_WASH_REC_SIZE_VO1();
            MNJ_ISSUEREC_WASH_REC_SIZE_VORowImpl SizesRow =
                (MNJ_ISSUEREC_WASH_REC_SIZE_VORowImpl)vold.getCurrentRow();

            try {
                HeaderId = HeaderRow.getHeaderId().toString();
            } catch (Exception e) {
                // TODO: Add catch code
                HeaderId = null;
                e.printStackTrace();
            }

            try {
                LineId = HeaderRow.getLineId().toString();
            } catch (Exception e) {
                // TODO: Add catch code
                LineId = null;
                e.printStackTrace();
            }

            try {
                DetailId = SizesRow.getRecevingSizeDet().toString();
            } catch (Exception e) {
                // TODO: Add catch code
                DetailId = null;
                e.printStackTrace();
            }

            try {
                BPO = HeaderRow.getAttribute1().toString();
            } catch (NullPointerException e) {
                BPO = null;
            }

            System.out.println("BPO is.... " + BPO);

            try {
                STN = HeaderRow.getAttribute2().toString();
            } catch (NullPointerException e) {
                STN = null;
            }
            System.out.println("STN is.... " + STN);

            try {
                Color = HeaderRow.getAttribute3().toString();
            } catch (NullPointerException e) {
                Color = null;
            }
            System.out.println("Color is.... " + Color);

            ViewObject voLineBPO =
                createViewObjectFromQueryStmt("voLineBPOC", "select distinct (select hca.CUST_ACCOUNT_ID \n" +
                    "                       from hz_parties hp, hz_cust_accounts hca ,ar_customers ac\n" +
                    "                       where hp.party_id = hca.party_id\n" + 
                    "                    AND hca.cust_account_id = ac.customer_id\n" + 
                    "                    AND hp.known_as IS NOT NULL\n" + 
                    "                    AND ac.status = 'A'\n" + 
                    "                    AND ac.customer_name_phonetic = 'M'\n" +
                    "                and hp.KNOWN_AS = h.attribute5) Buyer_id," +
                    "h.style_name ,h.season " +
                    "from MNJ_MFG_ISSUE_REC_WASH_H h\n" +
                    "                where header_id =" + "" + HeaderId);
            voLineBPO.first();

            System.out.println("Query of Run time Query is...." +
                               voLineBPO.getQuery());

            BuyerId = voLineBPO.getCurrentRow().getAttribute(0).toString();
            Style = voLineBPO.getCurrentRow().getAttribute(1).toString();
            Season = voLineBPO.getCurrentRow().getAttribute(2).toString();

            System.out.println("Parameters are is... " + BuyerId + Style +
                               Season);

            voLineBPO.remove();

            if (CheckSizes(BuyerId, Style, Season, BPO, STN, Color) == 1) {
                FacesContext context = FacesContext.getCurrentInstance();
                FacesMessage message =
                    new FacesMessage(FacesMessage.SEVERITY_ERROR,
                                     "Can not delete record as data exist in Delivery Sizes Tab....",
                                     "");
                //new FacesMessage("Delivery Size Quantity should not be greater than Delivery Quantity...");
                context.addMessage(null, message);
            } else {


                System.out.println("Detail Id is ......" + DetailId);
                Integer PHeaderId = Integer.parseInt(DetailId);
                CallableStatement plSqlBlock = null;
                String Statement =
                    "BEGIN DELETE FROM MNJ_ISSUEREC_WASH_REC_SIZE WHERE RECEVING_SIZE_DET = " +
                    PHeaderId + ";" + "COMMIT; END;";
                plSqlBlock =
                        getDBTransaction().createCallableStatement(Statement,
                                                                   0);
                try {
                    plSqlBlock.execute();
                    vo.executeQuery();

                } catch (SQLException e) {
                    e.printStackTrace();
                }


                FacesContext context = FacesContext.getCurrentInstance();
                FacesMessage message = new FacesMessage("Record Deleted...");
                context.addMessage(null, message);
            }
        } catch (Exception e) {
            // TODO: Add catch code

            e.printStackTrace();
        }


        getDBTransaction().commit();

    }

    public int CheckSizes(String BuyerId, String Style, String Season,
                          String BPO, String STN, String Color) {

        Map sessionScope = ADFContext.getCurrent().getSessionScope();

        String orgId = (String)sessionScope.get("orgId");
        System.out.println("Org ID is...." + orgId);

        int count = 0;
        count =
                (Integer)callStoredFunction(INTEGER, "mnj_washing_delete_validation.check_sizes(?, ?, ?, ?, ?,?)",
                                            new Object[] { BuyerId, Style,
                                                           Season, BPO, STN,
                                                           Color });

        return count;
    }

    public void check_rec_qty() {

        getDBTransaction().commit();
        String BPO = null;
        String STN = null;
        String BuyerId = null;
        String Style = null;
        String Season = null;
        String Color = null;

        System.out.println("In method check_rec_qty.....");

        try {
            ViewObject vo = getMNJ_ISSUE_REC_WASH_DEL_L_VO1();
            MNJ_ISSUE_REC_WASH_DEL_L_VORowImpl HeaderRow =
                (MNJ_ISSUE_REC_WASH_DEL_L_VORowImpl)vo.getCurrentRow();


            try {
                BPO = HeaderRow.getAttribute1().toString();
            } catch (NullPointerException e) {
                BPO = null;
            }

            System.out.println("BPO is.... " + BPO);

            try {
                STN = HeaderRow.getAttribute2().toString();
            } catch (NullPointerException e) {
                STN = null;
            }
            System.out.println("STN is.... " + STN);

            try {
                Color = HeaderRow.getAttribute3().toString();
            } catch (NullPointerException e) {
                Color = null;
            }
            System.out.println("Color is.... " + Color);

            try {
                BuyerId = HeaderRow.getBuyerId().toString();
            } catch (NullPointerException e) {
                BuyerId = null;
            }
            System.out.println("BuyerId is.... " + BuyerId);

            try {
                Style = HeaderRow.getAttribute5().toString();
            } catch (NullPointerException e) {
                Style = null;
            }
            System.out.println("Style is.... " + Style);

            try {
                Season = HeaderRow.getAttribute4().toString();
            } catch (NullPointerException e) {
                Season = null;
            }
            System.out.println("Season is.... " + Season);

            if (CheckQty(BuyerId, Style, Season, BPO, STN, Color) == 1) {
                FacesContext context = FacesContext.getCurrentInstance();
                FacesMessage message =
                    new FacesMessage(FacesMessage.SEVERITY_ERROR,
                                     "Delivery Quantity can not be more than Received Quantity...",
                                     "");
                context.addMessage(null, message);
            } else {
                getDBTransaction().commit();
            }

        } catch (Exception e) {
            // TODO: Add catch code

            e.printStackTrace();
        }
        getDBTransaction().commit();

    }

    public int CheckQty(String BuyerId, String Style, String Season,
                        String BPO, String STN, String Color) {

        Map sessionScope = ADFContext.getCurrent().getSessionScope();

        String orgId = (String)sessionScope.get("orgId");
        System.out.println("Org ID is...." + orgId);

        int count = 0;
        count =
                (Integer)callStoredFunction(INTEGER, "mnj_washing_delete_validation.check_rec_qty(?, ?, ?, ?, ?,?)",
                                            new Object[] { BuyerId, Style,
                                                           Season, BPO, STN,
                                                           Color });

        return count;
    }

    /**
     * Container's getter for operatingUnitsVo1.
     * @return operatingUnitsVo1
     */
    public operatingUnitsVoImpl getoperatingUnitsVo1() {
        return (operatingUnitsVoImpl)findViewObject("operatingUnitsVo1");
    }

    /**
     * Container's getter for NewHeaderVO1.
     * @return NewHeaderVO1
     */
    public ViewObjectImpl getNewHeaderVO1() {
        return (ViewObjectImpl)findViewObject("NewHeaderVO1");
    }

    /**
     * Container's getter for HeaderVO1.
     * @return HeaderVO1
     */
    public ViewObjectImpl getHeaderVO1() {
        return (ViewObjectImpl)findViewObject("HeaderVO1");
    }

    /**
     * Container's getter for NewHeaderViewLink1.
     * @return NewHeaderViewLink1
     */
    public ViewLinkImpl getNewHeaderViewLink1() {
        return (ViewLinkImpl)findViewLink("NewHeaderViewLink1");
    }


    /**
     * Container's getter for MNJ_ISSUE_REC_WASH_REC_L_VO1.
     * @return MNJ_ISSUE_REC_WASH_REC_L_VO1
     */
    public ViewObjectImpl getMNJ_ISSUE_REC_WASH_REC_L_VO1() {
        return (ViewObjectImpl)findViewObject("MNJ_ISSUE_REC_WASH_REC_L_VO1");
    }

    /**
     * Container's getter for MnjIssueRecWashRecFkLink1.
     * @return MnjIssueRecWashRecFkLink1
     */
    public ViewLinkImpl getMnjIssueRecWashRecFkLink1() {
        return (ViewLinkImpl)findViewLink("MnjIssueRecWashRecFkLink1");
    }

    /**
     * Container's getter for MNJ_ISSUEREC_WASH_REC_SIZE_VO1.
     * @return MNJ_ISSUEREC_WASH_REC_SIZE_VO1
     */
    public ViewObjectImpl getMNJ_ISSUEREC_WASH_REC_SIZE_VO1() {
        return (ViewObjectImpl)findViewObject("MNJ_ISSUEREC_WASH_REC_SIZE_VO1");
    }

    /**
     * Container's getter for MnjIssuerecWashRecSizeFkLink1.
     * @return MnjIssuerecWashRecSizeFkLink1
     */
    public ViewLinkImpl getMnjIssuerecWashRecSizeFkLink1() {
        return (ViewLinkImpl)findViewLink("MnjIssuerecWashRecSizeFkLink1");
    }

    /**
     * Container's getter for Pop_VO1.
     * @return Pop_VO1
     */
    public ViewObjectImpl getPop_VO1() {
        return (ViewObjectImpl)findViewObject("Pop_VO1");
    }

    /**
     * Container's getter for MNJ_ISSUE_REC_WASH_DEL_L_VO1.
     * @return MNJ_ISSUE_REC_WASH_DEL_L_VO1
     */
    public ViewObjectImpl getMNJ_ISSUE_REC_WASH_DEL_L_VO1() {
        return (ViewObjectImpl)findViewObject("MNJ_ISSUE_REC_WASH_DEL_L_VO1");
    }

    /**
     * Container's getter for MnjIssueRecWashDelLFkLink1.
     * @return MnjIssueRecWashDelLFkLink1
     */
    public ViewLinkImpl getMnjIssueRecWashDelLFkLink1() {
        return (ViewLinkImpl)findViewLink("MnjIssueRecWashDelLFkLink1");
    }

    /**
     * Container's getter for MNJ_ISSUEREC_WASH_DEL_SIZE_VO1.
     * @return MNJ_ISSUEREC_WASH_DEL_SIZE_VO1
     */
    public ViewObjectImpl getMNJ_ISSUEREC_WASH_DEL_SIZE_VO1() {
        return (ViewObjectImpl)findViewObject("MNJ_ISSUEREC_WASH_DEL_SIZE_VO1");
    }

    /**
     * Container's getter for MnjIssuerecWashDelSizeFkLink1.
     * @return MnjIssuerecWashDelSizeFkLink1
     */
    public ViewLinkImpl getMnjIssuerecWashDelSizeFkLink1() {
        return (ViewLinkImpl)findViewLink("MnjIssuerecWashDelSizeFkLink1");
    }

    /**
     * Container's getter for InvOrgVO1.
     * @return InvOrgVO1
     */
    public InvOrgVOImpl getInvOrgVO1() {
        return (InvOrgVOImpl)findViewObject("InvOrgVO1");
    }

    /**
     * Container's getter for Header_Org_VL1.
     * @return Header_Org_VL1
     */
    public ViewLinkImpl getHeader_Org_VL1() {
        return (ViewLinkImpl)findViewLink("Header_Org_VL1");
    }


    /**
     * Container's getter for FillBposVO1.
     * @return FillBposVO1
     */
    public FillBposVOImpl getFillBposVO1() {
        return (FillBposVOImpl)findViewObject("FillBposVO1");
    }
    
    public String validateIssueRecDate(){
        String docDate = null;
        String OpretnPlanDocDate = null;
        DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
        java.util.Date date1 = null;
        java.util.Date date2 = null;
        System.out.println("validateIssueRecDate");
        ViewObject hvo = this.getMNJ_ISSUE_REC_WASH_DEL_L_VO1();
        ViewObject nhvo = this.getNewHeaderVO1();
        Row nhRow = nhvo.getCurrentRow();
        Row row = null;
        try{
            docDate = nhRow.getAttribute("DocumentDate ").toString();
            System.out.println("docDate "+docDate);
        }catch(Exception e){
            docDate = null;    
        }
        String query = "SELECT  HeaderEO.DOC_DATE,LineEO.BUYER_ID,LineEO.STYLE,LineEO.SEASON,LineEO.COLOR FROM MNJ_MFG_WASH_QUALITY_L LineEO,MNJ_MFG_WASH_QUALITY_H HeaderEO WHERE LineEO.HEADER_ID =  HeaderEO.HEADER_ID";
        String BuyerId = null;
        String Season = null;
        String StyleName = null;
        String Color = null;
        String Wash = null;
        RowSetIterator hRowSetIterator = hvo.createRowSetIterator("hRowSetIterator");
        while(hRowSetIterator.hasNext()){
            row = hRowSetIterator.next();
            try{
                BuyerId = row.getAttribute("BuyerId").toString();
                System.out.println("BuyerId "+BuyerId);
            }catch(Exception e){
                BuyerId = null;    
            }
            try{
                Season = row.getAttribute("Attribute4").toString();
                System.out.println("Season "+Season);
            }catch(Exception e){
                Season = null;    
            }
            try{
                StyleName = row.getAttribute("Attribute5").toString();
                System.out.println("StyleName "+StyleName);
            }catch(Exception e){
                StyleName = null;    
            }
            try{
                Color = row.getAttribute("Attribute3").toString();
                System.out.println("Color "+Color);
            }catch(Exception e){
                Color = null;    
            }
//            try{
//                Wash = row.getAttribute("Wash").toString();
//                System.out.println("Wash "+Wash);
//            }catch(Exception e){
//                Wash = null;    
//            }
            
            ViewObject vo = createViewObjectFromQueryStmt("", query);
            vo.setWhereClause("BUYER_ID ="+BuyerId+" AND SEASON ='"+Season+"' AND STYLE='"+StyleName+"'AND COLOR = '"+Color+"'");
            vo.executeQuery();
            try{
                OpretnPlanDocDate = vo.first().getAttribute("DOC_DATE").toString();
                System.out.println("OpretnPlanDocDate "+OpretnPlanDocDate);
            }catch(Exception e){
                OpretnPlanDocDate = null;    
            }
            if(docDate != null && OpretnPlanDocDate != null){
                try{
                    date1 = df.parse(docDate);
                    System.out.println(date1);
                    date2 = df.parse(OpretnPlanDocDate);
                    System.out.println(date2);
                }catch (ParseException e) {
                    e.printStackTrace();
                    hRowSetIterator.closeRowSetIterator();
                    return "false";
                }
                if(date1.compareTo(date2) < 0){
                    //System.out.println("oiu");
                    hRowSetIterator.closeRowSetIterator();
                    showMessage("Document Date should be after Washing Document Date.");
                    return "false";
                }
            }
        }
        hRowSetIterator.closeRowSetIterator();
        return "true";
    }
    
    public String showMessage(String messageText ) {
        //String messageText=”A prgramatic af:message”;
        FacesMessage fm = new FacesMessage(messageText);
        /**
         * set the type of the message.
         * Valid types: error, fatal,info,warning
         */
        fm.setSeverity(FacesMessage.SEVERITY_ERROR);
        FacesContext context = FacesContext.getCurrentInstance();
        context.addMessage(null, fm);
          return null;
    }

    /**
     * Container's getter for Receipt_Challan_LOV1.
     * @return Receipt_Challan_LOV1
     */
    public ViewObjectImpl getReceipt_Challan_LOV1() {
        return (ViewObjectImpl)findViewObject("Receipt_Challan_LOV1");
    }

    /**
     * Container's getter for WashingRecDelFilterVo1.
     * @return WashingRecDelFilterVo1
     */
    public ViewObjectImpl getWashingRecDelFilterVo1() {
        return (ViewObjectImpl)findViewObject("WashingRecDelFilterVo1");
    }
}
