package mnj.mfg.model.views;

import mnj.mfg.model.entities.HeaderEOImpl;

import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Feb 07 12:19:26 PKT 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class HeaderVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        HeaderId {
            public Object get(HeaderVORowImpl obj) {
                return obj.getHeaderId();
            }

            public void put(HeaderVORowImpl obj, Object value) {
                obj.setHeaderId((Number)value);
            }
        }
        ,
        ReceiveNo {
            public Object get(HeaderVORowImpl obj) {
                return obj.getReceiveNo();
            }

            public void put(HeaderVORowImpl obj, Object value) {
                obj.setReceiveNo((String)value);
            }
        }
        ,
        InvoiceNo {
            public Object get(HeaderVORowImpl obj) {
                return obj.getInvoiceNo();
            }

            public void put(HeaderVORowImpl obj, Object value) {
                obj.setInvoiceNo((String)value);
            }
        }
        ,
        Color {
            public Object get(HeaderVORowImpl obj) {
                return obj.getColor();
            }

            public void put(HeaderVORowImpl obj, Object value) {
                obj.setColor((String)value);
            }
        }
        ,
        BuyerId {
            public Object get(HeaderVORowImpl obj) {
                return obj.getBuyerId();
            }

            public void put(HeaderVORowImpl obj, Object value) {
                obj.setBuyerId((Number)value);
            }
        }
        ,
        StyleName {
            public Object get(HeaderVORowImpl obj) {
                return obj.getStyleName();
            }

            public void put(HeaderVORowImpl obj, Object value) {
                obj.setStyleName((String)value);
            }
        }
        ,
        Season {
            public Object get(HeaderVORowImpl obj) {
                return obj.getSeason();
            }

            public void put(HeaderVORowImpl obj, Object value) {
                obj.setSeason((String)value);
            }
        }
        ,
        DateOfGrn {
            public Object get(HeaderVORowImpl obj) {
                return obj.getDateOfGrn();
            }

            public void put(HeaderVORowImpl obj, Object value) {
                obj.setDateOfGrn((Date)value);
            }
        }
        ,
        CreatedBy {
            public Object get(HeaderVORowImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(HeaderVORowImpl obj, Object value) {
                obj.setCreatedBy((Number)value);
            }
        }
        ,
        CreationDate {
            public Object get(HeaderVORowImpl obj) {
                return obj.getCreationDate();
            }

            public void put(HeaderVORowImpl obj, Object value) {
                obj.setCreationDate((Date)value);
            }
        }
        ,
        LastUpdatedBy {
            public Object get(HeaderVORowImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(HeaderVORowImpl obj, Object value) {
                obj.setLastUpdatedBy((Number)value);
            }
        }
        ,
        LastUpdateDate {
            public Object get(HeaderVORowImpl obj) {
                return obj.getLastUpdateDate();
            }

            public void put(HeaderVORowImpl obj, Object value) {
                obj.setLastUpdateDate((Date)value);
            }
        }
        ,
        OrgId {
            public Object get(HeaderVORowImpl obj) {
                return obj.getOrgId();
            }

            public void put(HeaderVORowImpl obj, Object value) {
                obj.setOrgId((Number)value);
            }
        }
        ,
        HeaderNo {
            public Object get(HeaderVORowImpl obj) {
                return obj.getHeaderNo();
            }

            public void put(HeaderVORowImpl obj, Object value) {
                obj.setHeaderNo((Number)value);
            }
        }
        ,
        LotNumber {
            public Object get(HeaderVORowImpl obj) {
                return obj.getLotNumber();
            }

            public void put(HeaderVORowImpl obj, Object value) {
                obj.setLotNumber((Number)value);
            }
        }
        ,
        Attribute1 {
            public Object get(HeaderVORowImpl obj) {
                return obj.getAttribute1();
            }

            public void put(HeaderVORowImpl obj, Object value) {
                obj.setAttribute1((String)value);
            }
        }
        ,
        Attribute2 {
            public Object get(HeaderVORowImpl obj) {
                return obj.getAttribute2();
            }

            public void put(HeaderVORowImpl obj, Object value) {
                obj.setAttribute2((String)value);
            }
        }
        ,
        Attribute3 {
            public Object get(HeaderVORowImpl obj) {
                return obj.getAttribute3();
            }

            public void put(HeaderVORowImpl obj, Object value) {
                obj.setAttribute3((String)value);
            }
        }
        ,
        Attribute4 {
            public Object get(HeaderVORowImpl obj) {
                return obj.getAttribute4();
            }

            public void put(HeaderVORowImpl obj, Object value) {
                obj.setAttribute4((String)value);
            }
        }
        ,
        Attribute5 {
            public Object get(HeaderVORowImpl obj) {
                return obj.getAttribute5();
            }

            public void put(HeaderVORowImpl obj, Object value) {
                obj.setAttribute5((String)value);
            }
        }
        ,
        Attribute6 {
            public Object get(HeaderVORowImpl obj) {
                return obj.getAttribute6();
            }

            public void put(HeaderVORowImpl obj, Object value) {
                obj.setAttribute6((String)value);
            }
        }
        ,
        Attribute7 {
            public Object get(HeaderVORowImpl obj) {
                return obj.getAttribute7();
            }

            public void put(HeaderVORowImpl obj, Object value) {
                obj.setAttribute7((String)value);
            }
        }
        ,
        Attribute8 {
            public Object get(HeaderVORowImpl obj) {
                return obj.getAttribute8();
            }

            public void put(HeaderVORowImpl obj, Object value) {
                obj.setAttribute8((String)value);
            }
        }
        ,
        Attribute9 {
            public Object get(HeaderVORowImpl obj) {
                return obj.getAttribute9();
            }

            public void put(HeaderVORowImpl obj, Object value) {
                obj.setAttribute9((String)value);
            }
        }
        ,
        Attribute10 {
            public Object get(HeaderVORowImpl obj) {
                return obj.getAttribute10();
            }

            public void put(HeaderVORowImpl obj, Object value) {
                obj.setAttribute10((String)value);
            }
        }
        ,
        Attribute11 {
            public Object get(HeaderVORowImpl obj) {
                return obj.getAttribute11();
            }

            public void put(HeaderVORowImpl obj, Object value) {
                obj.setAttribute11((String)value);
            }
        }
        ,
        Attribute12 {
            public Object get(HeaderVORowImpl obj) {
                return obj.getAttribute12();
            }

            public void put(HeaderVORowImpl obj, Object value) {
                obj.setAttribute12((String)value);
            }
        }
        ,
        Attribute13 {
            public Object get(HeaderVORowImpl obj) {
                return obj.getAttribute13();
            }

            public void put(HeaderVORowImpl obj, Object value) {
                obj.setAttribute13((String)value);
            }
        }
        ,
        Attribute14 {
            public Object get(HeaderVORowImpl obj) {
                return obj.getAttribute14();
            }

            public void put(HeaderVORowImpl obj, Object value) {
                obj.setAttribute14((String)value);
            }
        }
        ,
        Attribute15 {
            public Object get(HeaderVORowImpl obj) {
                return obj.getAttribute15();
            }

            public void put(HeaderVORowImpl obj, Object value) {
                obj.setAttribute15((String)value);
            }
        }
        ,
        SalesorderId {
            public Object get(HeaderVORowImpl obj) {
                return obj.getSalesorderId();
            }

            public void put(HeaderVORowImpl obj, Object value) {
                obj.setSalesorderId((Number)value);
            }
        }
        ,
        TransactionType {
            public Object get(HeaderVORowImpl obj) {
                return obj.getTransactionType();
            }

            public void put(HeaderVORowImpl obj, Object value) {
                obj.setTransactionType((String)value);
            }
        }
        ,
        Transaction {
            public Object get(HeaderVORowImpl obj) {
                return obj.getTransaction();
            }

            public void put(HeaderVORowImpl obj, Object value) {
                obj.setTransaction((String)value);
            }
        }
        ,
        IrHeaderId {
            public Object get(HeaderVORowImpl obj) {
                return obj.getIrHeaderId();
            }

            public void put(HeaderVORowImpl obj, Object value) {
                obj.setIrHeaderId((Number)value);
            }
        }
        ,
        Remarks {
            public Object get(HeaderVORowImpl obj) {
                return obj.getRemarks();
            }

            public void put(HeaderVORowImpl obj, Object value) {
                obj.setRemarks((String)value);
            }
        }
        ,
        UpdateOn {
            public Object get(HeaderVORowImpl obj) {
                return obj.getUpdateOn();
            }

            public void put(HeaderVORowImpl obj, Object value) {
                obj.setUpdateOn((Date)value);
            }
        }
        ,
        ReceiptChallanNo {
            public Object get(HeaderVORowImpl obj) {
                return obj.getReceiptChallanNo();
            }

            public void put(HeaderVORowImpl obj, Object value) {
                obj.setReceiptChallanNo((String)value);
            }
        }
        ,
        Unit {
            public Object get(HeaderVORowImpl obj) {
                return obj.getUnit();
            }

            public void put(HeaderVORowImpl obj, Object value) {
                obj.setUnit((String)value);
            }
        }
        ,
        CurrentStyle {
            public Object get(HeaderVORowImpl obj) {
                return obj.getCurrentStyle();
            }

            public void put(HeaderVORowImpl obj, Object value) {
                obj.setCurrentStyle((String)value);
            }
        }
        ,
        CurrentSeason {
            public Object get(HeaderVORowImpl obj) {
                return obj.getCurrentSeason();
            }

            public void put(HeaderVORowImpl obj, Object value) {
                obj.setCurrentSeason((String)value);
            }
        }
        ,
        PocId {
            public Object get(HeaderVORowImpl obj) {
                return obj.getPocId();
            }

            public void put(HeaderVORowImpl obj, Object value) {
                obj.setPocId((Number)value);
            }
        }
        ,
        BuyerIdNew {
            public Object get(HeaderVORowImpl obj) {
                return obj.getBuyerIdNew();
            }

            public void put(HeaderVORowImpl obj, Object value) {
                obj.setBuyerIdNew((Number)value);
            }
        }
        ,
        StyleNew {
            public Object get(HeaderVORowImpl obj) {
                return obj.getStyleNew();
            }

            public void put(HeaderVORowImpl obj, Object value) {
                obj.setStyleNew((String)value);
            }
        }
        ,
        SeasonNew {
            public Object get(HeaderVORowImpl obj) {
                return obj.getSeasonNew();
            }

            public void put(HeaderVORowImpl obj, Object value) {
                obj.setSeasonNew((String)value);
            }
        }
        ,
        BuyerNew {
            public Object get(HeaderVORowImpl obj) {
                return obj.getBuyerNew();
            }

            public void put(HeaderVORowImpl obj, Object value) {
                obj.setBuyerNew((String)value);
            }
        }
        ,
        LineVO {
            public Object get(HeaderVORowImpl obj) {
                return obj.getLineVO();
            }

            public void put(HeaderVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        MNJ_ISSUE_REC_WASH_REC_L_VO {
            public Object get(HeaderVORowImpl obj) {
                return obj.getMNJ_ISSUE_REC_WASH_REC_L_VO();
            }

            public void put(HeaderVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        FillBposVO {
            public Object get(HeaderVORowImpl obj) {
                return obj.getFillBposVO();
            }

            public void put(HeaderVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        buyerLOV1 {
            public Object get(HeaderVORowImpl obj) {
                return obj.getbuyerLOV1();
            }

            public void put(HeaderVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        style1 {
            public Object get(HeaderVORowImpl obj) {
                return obj.getstyle1();
            }

            public void put(HeaderVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        CustomerLOV1 {
            public Object get(HeaderVORowImpl obj) {
                return obj.getCustomerLOV1();
            }

            public void put(HeaderVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        TransactionTypeVO1 {
            public Object get(HeaderVORowImpl obj) {
                return obj.getTransactionTypeVO1();
            }

            public void put(HeaderVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Receipt_Challan_LOV1 {
            public Object get(HeaderVORowImpl obj) {
                return obj.getReceipt_Challan_LOV1();
            }

            public void put(HeaderVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(HeaderVORowImpl object);

        public abstract void put(HeaderVORowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int HEADERID = AttributesEnum.HeaderId.index();
    public static final int RECEIVENO = AttributesEnum.ReceiveNo.index();
    public static final int INVOICENO = AttributesEnum.InvoiceNo.index();
    public static final int COLOR = AttributesEnum.Color.index();
    public static final int BUYERID = AttributesEnum.BuyerId.index();
    public static final int STYLENAME = AttributesEnum.StyleName.index();
    public static final int SEASON = AttributesEnum.Season.index();
    public static final int DATEOFGRN = AttributesEnum.DateOfGrn.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int ORGID = AttributesEnum.OrgId.index();
    public static final int HEADERNO = AttributesEnum.HeaderNo.index();
    public static final int LOTNUMBER = AttributesEnum.LotNumber.index();
    public static final int ATTRIBUTE1 = AttributesEnum.Attribute1.index();
    public static final int ATTRIBUTE2 = AttributesEnum.Attribute2.index();
    public static final int ATTRIBUTE3 = AttributesEnum.Attribute3.index();
    public static final int ATTRIBUTE4 = AttributesEnum.Attribute4.index();
    public static final int ATTRIBUTE5 = AttributesEnum.Attribute5.index();
    public static final int ATTRIBUTE6 = AttributesEnum.Attribute6.index();
    public static final int ATTRIBUTE7 = AttributesEnum.Attribute7.index();
    public static final int ATTRIBUTE8 = AttributesEnum.Attribute8.index();
    public static final int ATTRIBUTE9 = AttributesEnum.Attribute9.index();
    public static final int ATTRIBUTE10 = AttributesEnum.Attribute10.index();
    public static final int ATTRIBUTE11 = AttributesEnum.Attribute11.index();
    public static final int ATTRIBUTE12 = AttributesEnum.Attribute12.index();
    public static final int ATTRIBUTE13 = AttributesEnum.Attribute13.index();
    public static final int ATTRIBUTE14 = AttributesEnum.Attribute14.index();
    public static final int ATTRIBUTE15 = AttributesEnum.Attribute15.index();
    public static final int SALESORDERID = AttributesEnum.SalesorderId.index();
    public static final int TRANSACTIONTYPE = AttributesEnum.TransactionType.index();
    public static final int TRANSACTION = AttributesEnum.Transaction.index();
    public static final int IRHEADERID = AttributesEnum.IrHeaderId.index();
    public static final int REMARKS = AttributesEnum.Remarks.index();
    public static final int UPDATEON = AttributesEnum.UpdateOn.index();
    public static final int RECEIPTCHALLANNO = AttributesEnum.ReceiptChallanNo.index();
    public static final int UNIT = AttributesEnum.Unit.index();
    public static final int CURRENTSTYLE = AttributesEnum.CurrentStyle.index();
    public static final int CURRENTSEASON = AttributesEnum.CurrentSeason.index();
    public static final int POCID = AttributesEnum.PocId.index();
    public static final int BUYERIDNEW = AttributesEnum.BuyerIdNew.index();
    public static final int STYLENEW = AttributesEnum.StyleNew.index();
    public static final int SEASONNEW = AttributesEnum.SeasonNew.index();
    public static final int BUYERNEW = AttributesEnum.BuyerNew.index();
    public static final int LINEVO = AttributesEnum.LineVO.index();
    public static final int MNJ_ISSUE_REC_WASH_REC_L_VO = AttributesEnum.MNJ_ISSUE_REC_WASH_REC_L_VO.index();
    public static final int FILLBPOSVO = AttributesEnum.FillBposVO.index();
    public static final int BUYERLOV1 = AttributesEnum.buyerLOV1.index();
    public static final int STYLE1 = AttributesEnum.style1.index();
    public static final int CUSTOMERLOV1 = AttributesEnum.CustomerLOV1.index();
    public static final int TRANSACTIONTYPEVO1 = AttributesEnum.TransactionTypeVO1.index();
    public static final int RECEIPT_CHALLAN_LOV1 = AttributesEnum.Receipt_Challan_LOV1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public HeaderVORowImpl() {
    }

    /**
     * Gets HeaderEO entity object.
     * @return the HeaderEO
     */
    public HeaderEOImpl getHeaderEO() {
        return (HeaderEOImpl)getEntity(0);
    }

    /**
     * Gets the attribute value for HEADER_ID using the alias name HeaderId.
     * @return the HEADER_ID
     */
    public Number getHeaderId() {
        return (Number) getAttributeInternal(HEADERID);
    }

    /**
     * Sets <code>value</code> as attribute value for HEADER_ID using the alias name HeaderId.
     * @param value value to set the HEADER_ID
     */
    public void setHeaderId(Number value) {
        setAttributeInternal(HEADERID, value);
    }

    /**
     * Gets the attribute value for RECEIVE_NO using the alias name ReceiveNo.
     * @return the RECEIVE_NO
     */
    public String getReceiveNo() {
        return (String) getAttributeInternal(RECEIVENO);
    }

    /**
     * Sets <code>value</code> as attribute value for RECEIVE_NO using the alias name ReceiveNo.
     * @param value value to set the RECEIVE_NO
     */
    public void setReceiveNo(String value) {
        setAttributeInternal(RECEIVENO, value);
    }

    /**
     * Gets the attribute value for INVOICE_NO using the alias name InvoiceNo.
     * @return the INVOICE_NO
     */
    public String getInvoiceNo() {
        return (String) getAttributeInternal(INVOICENO);
    }

    /**
     * Sets <code>value</code> as attribute value for INVOICE_NO using the alias name InvoiceNo.
     * @param value value to set the INVOICE_NO
     */
    public void setInvoiceNo(String value) {
        setAttributeInternal(INVOICENO, value);
    }

    /**
     * Gets the attribute value for COLOR using the alias name Color.
     * @return the COLOR
     */
    public String getColor() {
        return (String) getAttributeInternal(COLOR);
    }

    /**
     * Sets <code>value</code> as attribute value for COLOR using the alias name Color.
     * @param value value to set the COLOR
     */
    public void setColor(String value) {
        setAttributeInternal(COLOR, value);
    }

    /**
     * Gets the attribute value for BUYER_ID using the alias name BuyerId.
     * @return the BUYER_ID
     */
    public Number getBuyerId() {
        return (Number) getAttributeInternal(BUYERID);
    }

    /**
     * Sets <code>value</code> as attribute value for BUYER_ID using the alias name BuyerId.
     * @param value value to set the BUYER_ID
     */
    public void setBuyerId(Number value) {
        setAttributeInternal(BUYERID, value);
    }

    /**
     * Gets the attribute value for STYLE_NAME using the alias name StyleName.
     * @return the STYLE_NAME
     */
    public String getStyleName() {
        return (String) getAttributeInternal(STYLENAME);
    }

    /**
     * Sets <code>value</code> as attribute value for STYLE_NAME using the alias name StyleName.
     * @param value value to set the STYLE_NAME
     */
    public void setStyleName(String value) {
        setAttributeInternal(STYLENAME, value);
    }

    /**
     * Gets the attribute value for SEASON using the alias name Season.
     * @return the SEASON
     */
    public String getSeason() {
        return (String) getAttributeInternal(SEASON);
    }

    /**
     * Sets <code>value</code> as attribute value for SEASON using the alias name Season.
     * @param value value to set the SEASON
     */
    public void setSeason(String value) {
        setAttributeInternal(SEASON, value);
    }

    /**
     * Gets the attribute value for DATE_OF_GRN using the alias name DateOfGrn.
     * @return the DATE_OF_GRN
     */
    public Date getDateOfGrn() {
        return (Date) getAttributeInternal(DATEOFGRN);
    }

    /**
     * Sets <code>value</code> as attribute value for DATE_OF_GRN using the alias name DateOfGrn.
     * @param value value to set the DATE_OF_GRN
     */
    public void setDateOfGrn(Date value) {
        setAttributeInternal(DATEOFGRN, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public Number getCreatedBy() {
        return (Number) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy.
     * @param value value to set the CREATED_BY
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CREATION_DATE using the alias name CreationDate.
     * @return the CREATION_DATE
     */
    public Date getCreationDate() {
        return (Date) getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATION_DATE using the alias name CreationDate.
     * @param value value to set the CREATION_DATE
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @return the LAST_UPDATED_BY
     */
    public Number getLastUpdatedBy() {
        return (Number) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @param value value to set the LAST_UPDATED_BY
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @return the LAST_UPDATE_DATE
     */
    public Date getLastUpdateDate() {
        return (Date) getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @param value value to set the LAST_UPDATE_DATE
     */
    public void setLastUpdateDate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**
     * Gets the attribute value for ORG_ID using the alias name OrgId.
     * @return the ORG_ID
     */
    public Number getOrgId() {
        return (Number) getAttributeInternal(ORGID);
    }

    /**
     * Sets <code>value</code> as attribute value for ORG_ID using the alias name OrgId.
     * @param value value to set the ORG_ID
     */
    public void setOrgId(Number value) {
        setAttributeInternal(ORGID, value);
    }

    /**
     * Gets the attribute value for HEADER_NO using the alias name HeaderNo.
     * @return the HEADER_NO
     */
    public Number getHeaderNo() {
        return (Number) getAttributeInternal(HEADERNO);
    }

    /**
     * Sets <code>value</code> as attribute value for HEADER_NO using the alias name HeaderNo.
     * @param value value to set the HEADER_NO
     */
    public void setHeaderNo(Number value) {
        setAttributeInternal(HEADERNO, value);
    }

    /**
     * Gets the attribute value for LOT_NUMBER using the alias name LotNumber.
     * @return the LOT_NUMBER
     */
    public Number getLotNumber() {
        return (Number) getAttributeInternal(LOTNUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for LOT_NUMBER using the alias name LotNumber.
     * @param value value to set the LOT_NUMBER
     */
    public void setLotNumber(Number value) {
        setAttributeInternal(LOTNUMBER, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE1 using the alias name Attribute1.
     * @return the ATTRIBUTE1
     */
    public String getAttribute1() {
        return (String) getAttributeInternal(ATTRIBUTE1);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE1 using the alias name Attribute1.
     * @param value value to set the ATTRIBUTE1
     */
    public void setAttribute1(String value) {
        setAttributeInternal(ATTRIBUTE1, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE2 using the alias name Attribute2.
     * @return the ATTRIBUTE2
     */
    public String getAttribute2() {
        return (String) getAttributeInternal(ATTRIBUTE2);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE2 using the alias name Attribute2.
     * @param value value to set the ATTRIBUTE2
     */
    public void setAttribute2(String value) {
        setAttributeInternal(ATTRIBUTE2, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE3 using the alias name Attribute3.
     * @return the ATTRIBUTE3
     */
    public String getAttribute3() {
        return (String) getAttributeInternal(ATTRIBUTE3);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE3 using the alias name Attribute3.
     * @param value value to set the ATTRIBUTE3
     */
    public void setAttribute3(String value) {
        setAttributeInternal(ATTRIBUTE3, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE4 using the alias name Attribute4.
     * @return the ATTRIBUTE4
     */
    public String getAttribute4() {
        return (String) getAttributeInternal(ATTRIBUTE4);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE4 using the alias name Attribute4.
     * @param value value to set the ATTRIBUTE4
     */
    public void setAttribute4(String value) {
        setAttributeInternal(ATTRIBUTE4, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE5 using the alias name Attribute5.
     * @return the ATTRIBUTE5
     */
    public String getAttribute5() {
        return (String) getAttributeInternal(ATTRIBUTE5);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE5 using the alias name Attribute5.
     * @param value value to set the ATTRIBUTE5
     */
    public void setAttribute5(String value) {
        setAttributeInternal(ATTRIBUTE5, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE6 using the alias name Attribute6.
     * @return the ATTRIBUTE6
     */
    public String getAttribute6() {
        return (String) getAttributeInternal(ATTRIBUTE6);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE6 using the alias name Attribute6.
     * @param value value to set the ATTRIBUTE6
     */
    public void setAttribute6(String value) {
        setAttributeInternal(ATTRIBUTE6, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE7 using the alias name Attribute7.
     * @return the ATTRIBUTE7
     */
    public String getAttribute7() {
        return (String) getAttributeInternal(ATTRIBUTE7);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE7 using the alias name Attribute7.
     * @param value value to set the ATTRIBUTE7
     */
    public void setAttribute7(String value) {
        setAttributeInternal(ATTRIBUTE7, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE8 using the alias name Attribute8.
     * @return the ATTRIBUTE8
     */
    public String getAttribute8() {
        return (String) getAttributeInternal(ATTRIBUTE8);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE8 using the alias name Attribute8.
     * @param value value to set the ATTRIBUTE8
     */
    public void setAttribute8(String value) {
        setAttributeInternal(ATTRIBUTE8, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE9 using the alias name Attribute9.
     * @return the ATTRIBUTE9
     */
    public String getAttribute9() {
        return (String) getAttributeInternal(ATTRIBUTE9);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE9 using the alias name Attribute9.
     * @param value value to set the ATTRIBUTE9
     */
    public void setAttribute9(String value) {
        setAttributeInternal(ATTRIBUTE9, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE10 using the alias name Attribute10.
     * @return the ATTRIBUTE10
     */
    public String getAttribute10() {
        return (String) getAttributeInternal(ATTRIBUTE10);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE10 using the alias name Attribute10.
     * @param value value to set the ATTRIBUTE10
     */
    public void setAttribute10(String value) {
        setAttributeInternal(ATTRIBUTE10, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE11 using the alias name Attribute11.
     * @return the ATTRIBUTE11
     */
    public String getAttribute11() {
        return (String) getAttributeInternal(ATTRIBUTE11);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE11 using the alias name Attribute11.
     * @param value value to set the ATTRIBUTE11
     */
    public void setAttribute11(String value) {
        setAttributeInternal(ATTRIBUTE11, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE12 using the alias name Attribute12.
     * @return the ATTRIBUTE12
     */
    public String getAttribute12() {
        return (String) getAttributeInternal(ATTRIBUTE12);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE12 using the alias name Attribute12.
     * @param value value to set the ATTRIBUTE12
     */
    public void setAttribute12(String value) {
        setAttributeInternal(ATTRIBUTE12, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE13 using the alias name Attribute13.
     * @return the ATTRIBUTE13
     */
    public String getAttribute13() {
        return (String) getAttributeInternal(ATTRIBUTE13);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE13 using the alias name Attribute13.
     * @param value value to set the ATTRIBUTE13
     */
    public void setAttribute13(String value) {
        setAttributeInternal(ATTRIBUTE13, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE14 using the alias name Attribute14.
     * @return the ATTRIBUTE14
     */
    public String getAttribute14() {
        return (String) getAttributeInternal(ATTRIBUTE14);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE14 using the alias name Attribute14.
     * @param value value to set the ATTRIBUTE14
     */
    public void setAttribute14(String value) {
        setAttributeInternal(ATTRIBUTE14, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE15 using the alias name Attribute15.
     * @return the ATTRIBUTE15
     */
    public String getAttribute15() {
        return (String) getAttributeInternal(ATTRIBUTE15);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE15 using the alias name Attribute15.
     * @param value value to set the ATTRIBUTE15
     */
    public void setAttribute15(String value) {
        setAttributeInternal(ATTRIBUTE15, value);
    }

    /**
     * Gets the attribute value for SALESORDER_ID using the alias name SalesorderId.
     * @return the SALESORDER_ID
     */
    public Number getSalesorderId() {
        return (Number) getAttributeInternal(SALESORDERID);
    }

    /**
     * Sets <code>value</code> as attribute value for SALESORDER_ID using the alias name SalesorderId.
     * @param value value to set the SALESORDER_ID
     */
    public void setSalesorderId(Number value) {
        setAttributeInternal(SALESORDERID, value);
    }

    /**
     * Gets the attribute value for TRANSACTION_TYPE using the alias name TransactionType.
     * @return the TRANSACTION_TYPE
     */
    public String getTransactionType() {
        return (String) getAttributeInternal(TRANSACTIONTYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for TRANSACTION_TYPE using the alias name TransactionType.
     * @param value value to set the TRANSACTION_TYPE
     */
    public void setTransactionType(String value) {
        setAttributeInternal(TRANSACTIONTYPE, value);
    }

    /**
     * Gets the attribute value for TRANSACTION using the alias name Transaction.
     * @return the TRANSACTION
     */
    public String getTransaction() {
        return (String) getAttributeInternal(TRANSACTION);
    }

    /**
     * Sets <code>value</code> as attribute value for TRANSACTION using the alias name Transaction.
     * @param value value to set the TRANSACTION
     */
    public void setTransaction(String value) {
        setAttributeInternal(TRANSACTION, value);
    }

    /**
     * Gets the attribute value for IR_HEADER_ID using the alias name IrHeaderId.
     * @return the IR_HEADER_ID
     */
    public Number getIrHeaderId() {
        return (Number) getAttributeInternal(IRHEADERID);
    }

    /**
     * Sets <code>value</code> as attribute value for IR_HEADER_ID using the alias name IrHeaderId.
     * @param value value to set the IR_HEADER_ID
     */
    public void setIrHeaderId(Number value) {
        setAttributeInternal(IRHEADERID, value);
    }

    /**
     * Gets the attribute value for REMARKS using the alias name Remarks.
     * @return the REMARKS
     */
    public String getRemarks() {
        return (String) getAttributeInternal(REMARKS);
    }

    /**
     * Sets <code>value</code> as attribute value for REMARKS using the alias name Remarks.
     * @param value value to set the REMARKS
     */
    public void setRemarks(String value) {
        setAttributeInternal(REMARKS, value);
    }

    /**
     * Gets the attribute value for UPDATE_ON using the alias name UpdateOn.
     * @return the UPDATE_ON
     */
    public Date getUpdateOn() {
        return (Date) getAttributeInternal(UPDATEON);
    }

    /**
     * Sets <code>value</code> as attribute value for UPDATE_ON using the alias name UpdateOn.
     * @param value value to set the UPDATE_ON
     */
    public void setUpdateOn(Date value) {
        setAttributeInternal(UPDATEON, value);
    }

    /**
     * Gets the attribute value for RECEIPT_CHALLAN_NO using the alias name ReceiptChallanNo.
     * @return the RECEIPT_CHALLAN_NO
     */
    public String getReceiptChallanNo() {
        return (String) getAttributeInternal(RECEIPTCHALLANNO);
    }

    /**
     * Sets <code>value</code> as attribute value for RECEIPT_CHALLAN_NO using the alias name ReceiptChallanNo.
     * @param value value to set the RECEIPT_CHALLAN_NO
     */
    public void setReceiptChallanNo(String value) {
        setAttributeInternal(RECEIPTCHALLANNO, value);
    }

    /**
     * Gets the attribute value for UNIT using the alias name Unit.
     * @return the UNIT
     */
    public String getUnit() {
        return (String) getAttributeInternal(UNIT);
    }

    /**
     * Sets <code>value</code> as attribute value for UNIT using the alias name Unit.
     * @param value value to set the UNIT
     */
    public void setUnit(String value) {
        setAttributeInternal(UNIT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CurrentStyle.
     * @return the CurrentStyle
     */
    public String getCurrentStyle() {
        return (String) getAttributeInternal(CURRENTSTYLE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CurrentStyle.
     * @param value value to set the  CurrentStyle
     */
    public void setCurrentStyle(String value) {
        setAttributeInternal(CURRENTSTYLE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CurrentSeason.
     * @return the CurrentSeason
     */
    public String getCurrentSeason() {
        return (String) getAttributeInternal(CURRENTSEASON);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CurrentSeason.
     * @param value value to set the  CurrentSeason
     */
    public void setCurrentSeason(String value) {
        setAttributeInternal(CURRENTSEASON, value);
    }

    /**
     * Gets the attribute value for POC_ID using the alias name PocId.
     * @return the POC_ID
     */
    public Number getPocId() {
        return (Number) getAttributeInternal(POCID);
    }

    /**
     * Sets <code>value</code> as attribute value for POC_ID using the alias name PocId.
     * @param value value to set the POC_ID
     */
    public void setPocId(Number value) {
        setAttributeInternal(POCID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute BuyerIdNew.
     * @return the BuyerIdNew
     */
    public Number getBuyerIdNew() {
        return (Number) getAttributeInternal(BUYERIDNEW);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute BuyerIdNew.
     * @param value value to set the  BuyerIdNew
     */
    public void setBuyerIdNew(Number value) {
        setAttributeInternal(BUYERIDNEW, value);
    }

    /**
     * Gets the attribute value for the calculated attribute StyleNew.
     * @return the StyleNew
     */
    public String getStyleNew() {
        return (String) getAttributeInternal(STYLENEW);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute StyleNew.
     * @param value value to set the  StyleNew
     */
    public void setStyleNew(String value) {
        setAttributeInternal(STYLENEW, value);
    }

    /**
     * Gets the attribute value for the calculated attribute SeasonNew.
     * @return the SeasonNew
     */
    public String getSeasonNew() {
        return (String) getAttributeInternal(SEASONNEW);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute SeasonNew.
     * @param value value to set the  SeasonNew
     */
    public void setSeasonNew(String value) {
        setAttributeInternal(SEASONNEW, value);
    }

    /**
     * Gets the attribute value for the calculated attribute BuyerNew.
     * @return the BuyerNew
     */
    public String getBuyerNew() {
        return (String) getAttributeInternal(BUYERNEW);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute BuyerNew.
     * @param value value to set the  BuyerNew
     */
    public void setBuyerNew(String value) {
        setAttributeInternal(BUYERNEW, value);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link LineVO.
     */
    public RowIterator getLineVO() {
        return (RowIterator)getAttributeInternal(LINEVO);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link MNJ_ISSUE_REC_WASH_REC_L_VO.
     */
    public RowIterator getMNJ_ISSUE_REC_WASH_REC_L_VO() {
        return (RowIterator)getAttributeInternal(MNJ_ISSUE_REC_WASH_REC_L_VO);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link FillBposVO.
     */
    public RowIterator getFillBposVO() {
        return (RowIterator)getAttributeInternal(FILLBPOSVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> buyerLOV1.
     */
    public RowSet getbuyerLOV1() {
        return (RowSet)getAttributeInternal(BUYERLOV1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> style1.
     */
    public RowSet getstyle1() {
        return (RowSet)getAttributeInternal(STYLE1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> CustomerLOV1.
     */
    public RowSet getCustomerLOV1() {
        return (RowSet)getAttributeInternal(CUSTOMERLOV1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> TransactionTypeVO1.
     */
    public RowSet getTransactionTypeVO1() {
        return (RowSet)getAttributeInternal(TRANSACTIONTYPEVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> Receipt_Challan_LOV1.
     */
    public RowSet getReceipt_Challan_LOV1() {
        return (RowSet)getAttributeInternal(RECEIPT_CHALLAN_LOV1);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
