package mnj.mfg.model.views;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Apr 12 12:43:57 PKT 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MNJ_ISSUE_REC_WASH_REC_L_VOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public MNJ_ISSUE_REC_WASH_REC_L_VOImpl() {
    }
}
