package mnj.mfg.model.views;

import mnj.mfg.model.entities.MNJ_ISSUE_REC_WASH_DEL_L_EOImpl;

import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Feb 21 16:11:41 PKT 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MNJ_ISSUE_REC_WASH_DEL_L_VORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        IrHeaderId {
            public Object get(MNJ_ISSUE_REC_WASH_DEL_L_VORowImpl obj) {
                return obj.getIrHeaderId();
            }

            public void put(MNJ_ISSUE_REC_WASH_DEL_L_VORowImpl obj,
                            Object value) {
                obj.setIrHeaderId((Number)value);
            }
        }
        ,
        LineId {
            public Object get(MNJ_ISSUE_REC_WASH_DEL_L_VORowImpl obj) {
                return obj.getLineId();
            }

            public void put(MNJ_ISSUE_REC_WASH_DEL_L_VORowImpl obj,
                            Object value) {
                obj.setLineId((Number)value);
            }
        }
        ,
        Quantity {
            public Object get(MNJ_ISSUE_REC_WASH_DEL_L_VORowImpl obj) {
                return obj.getQuantity();
            }

            public void put(MNJ_ISSUE_REC_WASH_DEL_L_VORowImpl obj,
                            Object value) {
                obj.setQuantity((Number)value);
            }
        }
        ,
        CutDate {
            public Object get(MNJ_ISSUE_REC_WASH_DEL_L_VORowImpl obj) {
                return obj.getCutDate();
            }

            public void put(MNJ_ISSUE_REC_WASH_DEL_L_VORowImpl obj,
                            Object value) {
                obj.setCutDate((Date)value);
            }
        }
        ,
        StitchPrepDate {
            public Object get(MNJ_ISSUE_REC_WASH_DEL_L_VORowImpl obj) {
                return obj.getStitchPrepDate();
            }

            public void put(MNJ_ISSUE_REC_WASH_DEL_L_VORowImpl obj,
                            Object value) {
                obj.setStitchPrepDate((Date)value);
            }
        }
        ,
        WashingPlant {
            public Object get(MNJ_ISSUE_REC_WASH_DEL_L_VORowImpl obj) {
                return obj.getWashingPlant();
            }

            public void put(MNJ_ISSUE_REC_WASH_DEL_L_VORowImpl obj,
                            Object value) {
                obj.setWashingPlant((String)value);
            }
        }
        ,
        SendWashDate {
            public Object get(MNJ_ISSUE_REC_WASH_DEL_L_VORowImpl obj) {
                return obj.getSendWashDate();
            }

            public void put(MNJ_ISSUE_REC_WASH_DEL_L_VORowImpl obj,
                            Object value) {
                obj.setSendWashDate((Date)value);
            }
        }
        ,
        SendBy {
            public Object get(MNJ_ISSUE_REC_WASH_DEL_L_VORowImpl obj) {
                return obj.getSendBy();
            }

            public void put(MNJ_ISSUE_REC_WASH_DEL_L_VORowImpl obj,
                            Object value) {
                obj.setSendBy((String)value);
            }
        }
        ,
        CarriedBy {
            public Object get(MNJ_ISSUE_REC_WASH_DEL_L_VORowImpl obj) {
                return obj.getCarriedBy();
            }

            public void put(MNJ_ISSUE_REC_WASH_DEL_L_VORowImpl obj,
                            Object value) {
                obj.setCarriedBy((String)value);
            }
        }
        ,
        DelChallanNo {
            public Object get(MNJ_ISSUE_REC_WASH_DEL_L_VORowImpl obj) {
                return obj.getDelChallanNo();
            }

            public void put(MNJ_ISSUE_REC_WASH_DEL_L_VORowImpl obj,
                            Object value) {
                obj.setDelChallanNo((String)value);
            }
        }
        ,
        Remarks {
            public Object get(MNJ_ISSUE_REC_WASH_DEL_L_VORowImpl obj) {
                return obj.getRemarks();
            }

            public void put(MNJ_ISSUE_REC_WASH_DEL_L_VORowImpl obj,
                            Object value) {
                obj.setRemarks((String)value);
            }
        }
        ,
        Attribute1 {
            public Object get(MNJ_ISSUE_REC_WASH_DEL_L_VORowImpl obj) {
                return obj.getAttribute1();
            }

            public void put(MNJ_ISSUE_REC_WASH_DEL_L_VORowImpl obj,
                            Object value) {
                obj.setAttribute1((String)value);
            }
        }
        ,
        Attribute2 {
            public Object get(MNJ_ISSUE_REC_WASH_DEL_L_VORowImpl obj) {
                return obj.getAttribute2();
            }

            public void put(MNJ_ISSUE_REC_WASH_DEL_L_VORowImpl obj,
                            Object value) {
                obj.setAttribute2((String)value);
            }
        }
        ,
        Attribute3 {
            public Object get(MNJ_ISSUE_REC_WASH_DEL_L_VORowImpl obj) {
                return obj.getAttribute3();
            }

            public void put(MNJ_ISSUE_REC_WASH_DEL_L_VORowImpl obj,
                            Object value) {
                obj.setAttribute3((String)value);
            }
        }
        ,
        Attribute4 {
            public Object get(MNJ_ISSUE_REC_WASH_DEL_L_VORowImpl obj) {
                return obj.getAttribute4();
            }

            public void put(MNJ_ISSUE_REC_WASH_DEL_L_VORowImpl obj,
                            Object value) {
                obj.setAttribute4((String)value);
            }
        }
        ,
        Attribute5 {
            public Object get(MNJ_ISSUE_REC_WASH_DEL_L_VORowImpl obj) {
                return obj.getAttribute5();
            }

            public void put(MNJ_ISSUE_REC_WASH_DEL_L_VORowImpl obj,
                            Object value) {
                obj.setAttribute5((String)value);
            }
        }
        ,
        Attribute6 {
            public Object get(MNJ_ISSUE_REC_WASH_DEL_L_VORowImpl obj) {
                return obj.getAttribute6();
            }

            public void put(MNJ_ISSUE_REC_WASH_DEL_L_VORowImpl obj,
                            Object value) {
                obj.setAttribute6((String)value);
            }
        }
        ,
        Attribute7 {
            public Object get(MNJ_ISSUE_REC_WASH_DEL_L_VORowImpl obj) {
                return obj.getAttribute7();
            }

            public void put(MNJ_ISSUE_REC_WASH_DEL_L_VORowImpl obj,
                            Object value) {
                obj.setAttribute7((String)value);
            }
        }
        ,
        Attribute8 {
            public Object get(MNJ_ISSUE_REC_WASH_DEL_L_VORowImpl obj) {
                return obj.getAttribute8();
            }

            public void put(MNJ_ISSUE_REC_WASH_DEL_L_VORowImpl obj,
                            Object value) {
                obj.setAttribute8((String)value);
            }
        }
        ,
        Attribute9 {
            public Object get(MNJ_ISSUE_REC_WASH_DEL_L_VORowImpl obj) {
                return obj.getAttribute9();
            }

            public void put(MNJ_ISSUE_REC_WASH_DEL_L_VORowImpl obj,
                            Object value) {
                obj.setAttribute9((String)value);
            }
        }
        ,
        Attribute10 {
            public Object get(MNJ_ISSUE_REC_WASH_DEL_L_VORowImpl obj) {
                return obj.getAttribute10();
            }

            public void put(MNJ_ISSUE_REC_WASH_DEL_L_VORowImpl obj,
                            Object value) {
                obj.setAttribute10((String)value);
            }
        }
        ,
        Attribute11 {
            public Object get(MNJ_ISSUE_REC_WASH_DEL_L_VORowImpl obj) {
                return obj.getAttribute11();
            }

            public void put(MNJ_ISSUE_REC_WASH_DEL_L_VORowImpl obj,
                            Object value) {
                obj.setAttribute11((String)value);
            }
        }
        ,
        Attribute12 {
            public Object get(MNJ_ISSUE_REC_WASH_DEL_L_VORowImpl obj) {
                return obj.getAttribute12();
            }

            public void put(MNJ_ISSUE_REC_WASH_DEL_L_VORowImpl obj,
                            Object value) {
                obj.setAttribute12((String)value);
            }
        }
        ,
        Attribute13 {
            public Object get(MNJ_ISSUE_REC_WASH_DEL_L_VORowImpl obj) {
                return obj.getAttribute13();
            }

            public void put(MNJ_ISSUE_REC_WASH_DEL_L_VORowImpl obj,
                            Object value) {
                obj.setAttribute13((String)value);
            }
        }
        ,
        Attribute14 {
            public Object get(MNJ_ISSUE_REC_WASH_DEL_L_VORowImpl obj) {
                return obj.getAttribute14();
            }

            public void put(MNJ_ISSUE_REC_WASH_DEL_L_VORowImpl obj,
                            Object value) {
                obj.setAttribute14((String)value);
            }
        }
        ,
        Attribute15 {
            public Object get(MNJ_ISSUE_REC_WASH_DEL_L_VORowImpl obj) {
                return obj.getAttribute15();
            }

            public void put(MNJ_ISSUE_REC_WASH_DEL_L_VORowImpl obj,
                            Object value) {
                obj.setAttribute15((String)value);
            }
        }
        ,
        SalesorderId {
            public Object get(MNJ_ISSUE_REC_WASH_DEL_L_VORowImpl obj) {
                return obj.getSalesorderId();
            }

            public void put(MNJ_ISSUE_REC_WASH_DEL_L_VORowImpl obj,
                            Object value) {
                obj.setSalesorderId((Number)value);
            }
        }
        ,
        LastUpdateDate {
            public Object get(MNJ_ISSUE_REC_WASH_DEL_L_VORowImpl obj) {
                return obj.getLastUpdateDate();
            }

            public void put(MNJ_ISSUE_REC_WASH_DEL_L_VORowImpl obj,
                            Object value) {
                obj.setLastUpdateDate((Date)value);
            }
        }
        ,
        LastUpdatedBy {
            public Object get(MNJ_ISSUE_REC_WASH_DEL_L_VORowImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(MNJ_ISSUE_REC_WASH_DEL_L_VORowImpl obj,
                            Object value) {
                obj.setLastUpdatedBy((Number)value);
            }
        }
        ,
        CreationDate {
            public Object get(MNJ_ISSUE_REC_WASH_DEL_L_VORowImpl obj) {
                return obj.getCreationDate();
            }

            public void put(MNJ_ISSUE_REC_WASH_DEL_L_VORowImpl obj,
                            Object value) {
                obj.setCreationDate((Date)value);
            }
        }
        ,
        CreatedBy {
            public Object get(MNJ_ISSUE_REC_WASH_DEL_L_VORowImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(MNJ_ISSUE_REC_WASH_DEL_L_VORowImpl obj,
                            Object value) {
                obj.setCreatedBy((Number)value);
            }
        }
        ,
        OrgId {
            public Object get(MNJ_ISSUE_REC_WASH_DEL_L_VORowImpl obj) {
                return obj.getOrgId();
            }

            public void put(MNJ_ISSUE_REC_WASH_DEL_L_VORowImpl obj,
                            Object value) {
                obj.setOrgId((Number)value);
            }
        }
        ,
        ChallanNo {
            public Object get(MNJ_ISSUE_REC_WASH_DEL_L_VORowImpl obj) {
                return obj.getChallanNo();
            }

            public void put(MNJ_ISSUE_REC_WASH_DEL_L_VORowImpl obj,
                            Object value) {
                obj.setChallanNo((Number)value);
            }
        }
        ,
        WashType {
            public Object get(MNJ_ISSUE_REC_WASH_DEL_L_VORowImpl obj) {
                return obj.getWashType();
            }

            public void put(MNJ_ISSUE_REC_WASH_DEL_L_VORowImpl obj,
                            Object value) {
                obj.setWashType((String)value);
            }
        }
        ,
        ProductionType {
            public Object get(MNJ_ISSUE_REC_WASH_DEL_L_VORowImpl obj) {
                return obj.getProductionType();
            }

            public void put(MNJ_ISSUE_REC_WASH_DEL_L_VORowImpl obj,
                            Object value) {
                obj.setProductionType((String)value);
            }
        }
        ,
        WashEmdPrintInv {
            public Object get(MNJ_ISSUE_REC_WASH_DEL_L_VORowImpl obj) {
                return obj.getWashEmdPrintInv();
            }

            public void put(MNJ_ISSUE_REC_WASH_DEL_L_VORowImpl obj,
                            Object value) {
                obj.setWashEmdPrintInv((Number)value);
            }
        }
        ,
        IssuanceDate {
            public Object get(MNJ_ISSUE_REC_WASH_DEL_L_VORowImpl obj) {
                return obj.getIssuanceDate();
            }

            public void put(MNJ_ISSUE_REC_WASH_DEL_L_VORowImpl obj,
                            Object value) {
                obj.setIssuanceDate((Date)value);
            }
        }
        ,
        IssuanceChallanNo {
            public Object get(MNJ_ISSUE_REC_WASH_DEL_L_VORowImpl obj) {
                return obj.getIssuanceChallanNo();
            }

            public void put(MNJ_ISSUE_REC_WASH_DEL_L_VORowImpl obj,
                            Object value) {
                obj.setIssuanceChallanNo((String)value);
            }
        }
        ,
        WashEmdPrintInvorg {
            public Object get(MNJ_ISSUE_REC_WASH_DEL_L_VORowImpl obj) {
                return obj.getWashEmdPrintInvorg();
            }

            public void put(MNJ_ISSUE_REC_WASH_DEL_L_VORowImpl obj,
                            Object value) {
                obj.setWashEmdPrintInvorg((String)value);
            }
        }
        ,
        DeliveryDate {
            public Object get(MNJ_ISSUE_REC_WASH_DEL_L_VORowImpl obj) {
                return obj.getDeliveryDate();
            }

            public void put(MNJ_ISSUE_REC_WASH_DEL_L_VORowImpl obj,
                            Object value) {
                obj.setDeliveryDate((Date)value);
            }
        }
        ,
        BuyerId {
            public Object get(MNJ_ISSUE_REC_WASH_DEL_L_VORowImpl obj) {
                return obj.getBuyerId();
            }

            public void put(MNJ_ISSUE_REC_WASH_DEL_L_VORowImpl obj,
                            Object value) {
                obj.setBuyerId((Number)value);
            }
        }
        ,
        BpoId {
            public Object get(MNJ_ISSUE_REC_WASH_DEL_L_VORowImpl obj) {
                return obj.getBpoId();
            }

            public void put(MNJ_ISSUE_REC_WASH_DEL_L_VORowImpl obj,
                            Object value) {
                obj.setBpoId((Number)value);
            }
        }
        ,
        SystemId {
            public Object get(MNJ_ISSUE_REC_WASH_DEL_L_VORowImpl obj) {
                return obj.getSystemId();
            }

            public void put(MNJ_ISSUE_REC_WASH_DEL_L_VORowImpl obj,
                            Object value) {
                obj.setSystemId((Number)value);
            }
        }
        ,
        BuyerNew {
            public Object get(MNJ_ISSUE_REC_WASH_DEL_L_VORowImpl obj) {
                return obj.getBuyerNew();
            }

            public void put(MNJ_ISSUE_REC_WASH_DEL_L_VORowImpl obj,
                            Object value) {
                obj.setBuyerNew((String)value);
            }
        }
        ,
        SeasonNew {
            public Object get(MNJ_ISSUE_REC_WASH_DEL_L_VORowImpl obj) {
                return obj.getSeasonNew();
            }

            public void put(MNJ_ISSUE_REC_WASH_DEL_L_VORowImpl obj,
                            Object value) {
                obj.setSeasonNew((String)value);
            }
        }
        ,
        StyleNew {
            public Object get(MNJ_ISSUE_REC_WASH_DEL_L_VORowImpl obj) {
                return obj.getStyleNew();
            }

            public void put(MNJ_ISSUE_REC_WASH_DEL_L_VORowImpl obj,
                            Object value) {
                obj.setStyleNew((String)value);
            }
        }
        ,
        ColorNew {
            public Object get(MNJ_ISSUE_REC_WASH_DEL_L_VORowImpl obj) {
                return obj.getColorNew();
            }

            public void put(MNJ_ISSUE_REC_WASH_DEL_L_VORowImpl obj,
                            Object value) {
                obj.setColorNew((String)value);
            }
        }
        ,
        WashNew {
            public Object get(MNJ_ISSUE_REC_WASH_DEL_L_VORowImpl obj) {
                return obj.getWashNew();
            }

            public void put(MNJ_ISSUE_REC_WASH_DEL_L_VORowImpl obj,
                            Object value) {
                obj.setWashNew((String)value);
            }
        }
        ,
        BpoNew {
            public Object get(MNJ_ISSUE_REC_WASH_DEL_L_VORowImpl obj) {
                return obj.getBpoNew();
            }

            public void put(MNJ_ISSUE_REC_WASH_DEL_L_VORowImpl obj,
                            Object value) {
                obj.setBpoNew((String)value);
            }
        }
        ,
        MNJ_ISSUEREC_WASH_DEL_SIZE_VO {
            public Object get(MNJ_ISSUE_REC_WASH_DEL_L_VORowImpl obj) {
                return obj.getMNJ_ISSUEREC_WASH_DEL_SIZE_VO();
            }

            public void put(MNJ_ISSUE_REC_WASH_DEL_L_VORowImpl obj,
                            Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        FillBposVO1 {
            public Object get(MNJ_ISSUE_REC_WASH_DEL_L_VORowImpl obj) {
                return obj.getFillBposVO1();
            }

            public void put(MNJ_ISSUE_REC_WASH_DEL_L_VORowImpl obj,
                            Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        WashTypeVO1 {
            public Object get(MNJ_ISSUE_REC_WASH_DEL_L_VORowImpl obj) {
                return obj.getWashTypeVO1();
            }

            public void put(MNJ_ISSUE_REC_WASH_DEL_L_VORowImpl obj,
                            Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        ProductionTypeVO1 {
            public Object get(MNJ_ISSUE_REC_WASH_DEL_L_VORowImpl obj) {
                return obj.getProductionTypeVO1();
            }

            public void put(MNJ_ISSUE_REC_WASH_DEL_L_VORowImpl obj,
                            Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(MNJ_ISSUE_REC_WASH_DEL_L_VORowImpl object);

        public abstract void put(MNJ_ISSUE_REC_WASH_DEL_L_VORowImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int IRHEADERID = AttributesEnum.IrHeaderId.index();
    public static final int LINEID = AttributesEnum.LineId.index();
    public static final int QUANTITY = AttributesEnum.Quantity.index();
    public static final int CUTDATE = AttributesEnum.CutDate.index();
    public static final int STITCHPREPDATE = AttributesEnum.StitchPrepDate.index();
    public static final int WASHINGPLANT = AttributesEnum.WashingPlant.index();
    public static final int SENDWASHDATE = AttributesEnum.SendWashDate.index();
    public static final int SENDBY = AttributesEnum.SendBy.index();
    public static final int CARRIEDBY = AttributesEnum.CarriedBy.index();
    public static final int DELCHALLANNO = AttributesEnum.DelChallanNo.index();
    public static final int REMARKS = AttributesEnum.Remarks.index();
    public static final int ATTRIBUTE1 = AttributesEnum.Attribute1.index();
    public static final int ATTRIBUTE2 = AttributesEnum.Attribute2.index();
    public static final int ATTRIBUTE3 = AttributesEnum.Attribute3.index();
    public static final int ATTRIBUTE4 = AttributesEnum.Attribute4.index();
    public static final int ATTRIBUTE5 = AttributesEnum.Attribute5.index();
    public static final int ATTRIBUTE6 = AttributesEnum.Attribute6.index();
    public static final int ATTRIBUTE7 = AttributesEnum.Attribute7.index();
    public static final int ATTRIBUTE8 = AttributesEnum.Attribute8.index();
    public static final int ATTRIBUTE9 = AttributesEnum.Attribute9.index();
    public static final int ATTRIBUTE10 = AttributesEnum.Attribute10.index();
    public static final int ATTRIBUTE11 = AttributesEnum.Attribute11.index();
    public static final int ATTRIBUTE12 = AttributesEnum.Attribute12.index();
    public static final int ATTRIBUTE13 = AttributesEnum.Attribute13.index();
    public static final int ATTRIBUTE14 = AttributesEnum.Attribute14.index();
    public static final int ATTRIBUTE15 = AttributesEnum.Attribute15.index();
    public static final int SALESORDERID = AttributesEnum.SalesorderId.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int ORGID = AttributesEnum.OrgId.index();
    public static final int CHALLANNO = AttributesEnum.ChallanNo.index();
    public static final int WASHTYPE = AttributesEnum.WashType.index();
    public static final int PRODUCTIONTYPE = AttributesEnum.ProductionType.index();
    public static final int WASHEMDPRINTINV = AttributesEnum.WashEmdPrintInv.index();
    public static final int ISSUANCEDATE = AttributesEnum.IssuanceDate.index();
    public static final int ISSUANCECHALLANNO = AttributesEnum.IssuanceChallanNo.index();
    public static final int WASHEMDPRINTINVORG = AttributesEnum.WashEmdPrintInvorg.index();
    public static final int DELIVERYDATE = AttributesEnum.DeliveryDate.index();
    public static final int BUYERID = AttributesEnum.BuyerId.index();
    public static final int BPOID = AttributesEnum.BpoId.index();
    public static final int SYSTEMID = AttributesEnum.SystemId.index();
    public static final int BUYERNEW = AttributesEnum.BuyerNew.index();
    public static final int SEASONNEW = AttributesEnum.SeasonNew.index();
    public static final int STYLENEW = AttributesEnum.StyleNew.index();
    public static final int COLORNEW = AttributesEnum.ColorNew.index();
    public static final int WASHNEW = AttributesEnum.WashNew.index();
    public static final int BPONEW = AttributesEnum.BpoNew.index();
    public static final int MNJ_ISSUEREC_WASH_DEL_SIZE_VO = AttributesEnum.MNJ_ISSUEREC_WASH_DEL_SIZE_VO.index();
    public static final int FILLBPOSVO1 = AttributesEnum.FillBposVO1.index();
    public static final int WASHTYPEVO1 = AttributesEnum.WashTypeVO1.index();
    public static final int PRODUCTIONTYPEVO1 = AttributesEnum.ProductionTypeVO1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public MNJ_ISSUE_REC_WASH_DEL_L_VORowImpl() {
    }

    /**
     * Gets MNJ_ISSUE_REC_WASH_DEL_L_EO entity object.
     * @return the MNJ_ISSUE_REC_WASH_DEL_L_EO
     */
    public MNJ_ISSUE_REC_WASH_DEL_L_EOImpl getMNJ_ISSUE_REC_WASH_DEL_L_EO() {
        return (MNJ_ISSUE_REC_WASH_DEL_L_EOImpl)getEntity(0);
    }

    /**
     * Gets the attribute value for IR_HEADER_ID using the alias name IrHeaderId.
     * @return the IR_HEADER_ID
     */
    public Number getIrHeaderId() {
        return (Number) getAttributeInternal(IRHEADERID);
    }

    /**
     * Sets <code>value</code> as attribute value for IR_HEADER_ID using the alias name IrHeaderId.
     * @param value value to set the IR_HEADER_ID
     */
    public void setIrHeaderId(Number value) {
        setAttributeInternal(IRHEADERID, value);
    }

    /**
     * Gets the attribute value for LINE_ID using the alias name LineId.
     * @return the LINE_ID
     */
    public Number getLineId() {
        return (Number) getAttributeInternal(LINEID);
    }

    /**
     * Sets <code>value</code> as attribute value for LINE_ID using the alias name LineId.
     * @param value value to set the LINE_ID
     */
    public void setLineId(Number value) {
        setAttributeInternal(LINEID, value);
    }

    /**
     * Gets the attribute value for QUANTITY using the alias name Quantity.
     * @return the QUANTITY
     */
    public Number getQuantity() {
        return (Number) getAttributeInternal(QUANTITY);
    }

    /**
     * Sets <code>value</code> as attribute value for QUANTITY using the alias name Quantity.
     * @param value value to set the QUANTITY
     */
    public void setQuantity(Number value) {
        setAttributeInternal(QUANTITY, value);
    }

    /**
     * Gets the attribute value for CUT_DATE using the alias name CutDate.
     * @return the CUT_DATE
     */
    public Date getCutDate() {
        return (Date) getAttributeInternal(CUTDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CUT_DATE using the alias name CutDate.
     * @param value value to set the CUT_DATE
     */
    public void setCutDate(Date value) {
        setAttributeInternal(CUTDATE, value);
    }

    /**
     * Gets the attribute value for STITCH_PREP_DATE using the alias name StitchPrepDate.
     * @return the STITCH_PREP_DATE
     */
    public Date getStitchPrepDate() {
        return (Date) getAttributeInternal(STITCHPREPDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for STITCH_PREP_DATE using the alias name StitchPrepDate.
     * @param value value to set the STITCH_PREP_DATE
     */
    public void setStitchPrepDate(Date value) {
        setAttributeInternal(STITCHPREPDATE, value);
    }

    /**
     * Gets the attribute value for WASHING_PLANT using the alias name WashingPlant.
     * @return the WASHING_PLANT
     */
    public String getWashingPlant() {
        return (String) getAttributeInternal(WASHINGPLANT);
    }

    /**
     * Sets <code>value</code> as attribute value for WASHING_PLANT using the alias name WashingPlant.
     * @param value value to set the WASHING_PLANT
     */
    public void setWashingPlant(String value) {
        setAttributeInternal(WASHINGPLANT, value);
    }

    /**
     * Gets the attribute value for SEND_WASH_DATE using the alias name SendWashDate.
     * @return the SEND_WASH_DATE
     */
    public Date getSendWashDate() {
        return (Date) getAttributeInternal(SENDWASHDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for SEND_WASH_DATE using the alias name SendWashDate.
     * @param value value to set the SEND_WASH_DATE
     */
    public void setSendWashDate(Date value) {
        setAttributeInternal(SENDWASHDATE, value);
    }

    /**
     * Gets the attribute value for SEND_BY using the alias name SendBy.
     * @return the SEND_BY
     */
    public String getSendBy() {
        return (String) getAttributeInternal(SENDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for SEND_BY using the alias name SendBy.
     * @param value value to set the SEND_BY
     */
    public void setSendBy(String value) {
        setAttributeInternal(SENDBY, value);
    }

    /**
     * Gets the attribute value for CARRIED_BY using the alias name CarriedBy.
     * @return the CARRIED_BY
     */
    public String getCarriedBy() {
        return (String) getAttributeInternal(CARRIEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CARRIED_BY using the alias name CarriedBy.
     * @param value value to set the CARRIED_BY
     */
    public void setCarriedBy(String value) {
        setAttributeInternal(CARRIEDBY, value);
    }

    /**
     * Gets the attribute value for DEL_CHALLAN_NO using the alias name DelChallanNo.
     * @return the DEL_CHALLAN_NO
     */
    public String getDelChallanNo() {
        return (String) getAttributeInternal(DELCHALLANNO);
    }

    /**
     * Sets <code>value</code> as attribute value for DEL_CHALLAN_NO using the alias name DelChallanNo.
     * @param value value to set the DEL_CHALLAN_NO
     */
    public void setDelChallanNo(String value) {
        setAttributeInternal(DELCHALLANNO, value);
    }

    /**
     * Gets the attribute value for REMARKS using the alias name Remarks.
     * @return the REMARKS
     */
    public String getRemarks() {
        return (String) getAttributeInternal(REMARKS);
    }

    /**
     * Sets <code>value</code> as attribute value for REMARKS using the alias name Remarks.
     * @param value value to set the REMARKS
     */
    public void setRemarks(String value) {
        setAttributeInternal(REMARKS, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE1 using the alias name Attribute1.
     * @return the ATTRIBUTE1
     */
    public String getAttribute1() {
        return (String) getAttributeInternal(ATTRIBUTE1);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE1 using the alias name Attribute1.
     * @param value value to set the ATTRIBUTE1
     */
    public void setAttribute1(String value) {
        setAttributeInternal(ATTRIBUTE1, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE2 using the alias name Attribute2.
     * @return the ATTRIBUTE2
     */
    public String getAttribute2() {
        return (String) getAttributeInternal(ATTRIBUTE2);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE2 using the alias name Attribute2.
     * @param value value to set the ATTRIBUTE2
     */
    public void setAttribute2(String value) {
        setAttributeInternal(ATTRIBUTE2, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE3 using the alias name Attribute3.
     * @return the ATTRIBUTE3
     */
    public String getAttribute3() {
        return (String) getAttributeInternal(ATTRIBUTE3);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE3 using the alias name Attribute3.
     * @param value value to set the ATTRIBUTE3
     */
    public void setAttribute3(String value) {
        setAttributeInternal(ATTRIBUTE3, value);
    }


    /**
     * Gets the attribute value for ATTRIBUTE4 using the alias name Attribute4.
     * @return the ATTRIBUTE4
     */
    public String getAttribute4() {
        return (String) getAttributeInternal(ATTRIBUTE4);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE4 using the alias name Attribute4.
     * @param value value to set the ATTRIBUTE4
     */
    public void setAttribute4(String value) {
        setAttributeInternal(ATTRIBUTE4, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE5 using the alias name Attribute5.
     * @return the ATTRIBUTE5
     */
    public String getAttribute5() {
        return (String) getAttributeInternal(ATTRIBUTE5);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE5 using the alias name Attribute5.
     * @param value value to set the ATTRIBUTE5
     */
    public void setAttribute5(String value) {
        setAttributeInternal(ATTRIBUTE5, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE6 using the alias name Attribute6.
     * @return the ATTRIBUTE6
     */
    public String getAttribute6() {
        return (String) getAttributeInternal(ATTRIBUTE6);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE6 using the alias name Attribute6.
     * @param value value to set the ATTRIBUTE6
     */
    public void setAttribute6(String value) {
        setAttributeInternal(ATTRIBUTE6, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE7 using the alias name Attribute7.
     * @return the ATTRIBUTE7
     */
    public String getAttribute7() {
        return (String) getAttributeInternal(ATTRIBUTE7);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE7 using the alias name Attribute7.
     * @param value value to set the ATTRIBUTE7
     */
    public void setAttribute7(String value) {
        setAttributeInternal(ATTRIBUTE7, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE8 using the alias name Attribute8.
     * @return the ATTRIBUTE8
     */
    public String getAttribute8() {
        return (String) getAttributeInternal(ATTRIBUTE8);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE8 using the alias name Attribute8.
     * @param value value to set the ATTRIBUTE8
     */
    public void setAttribute8(String value) {
        setAttributeInternal(ATTRIBUTE8, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE9 using the alias name Attribute9.
     * @return the ATTRIBUTE9
     */
    public String getAttribute9() {
        return (String) getAttributeInternal(ATTRIBUTE9);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE9 using the alias name Attribute9.
     * @param value value to set the ATTRIBUTE9
     */
    public void setAttribute9(String value) {
        setAttributeInternal(ATTRIBUTE9, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE10 using the alias name Attribute10.
     * @return the ATTRIBUTE10
     */
    public String getAttribute10() {
        return (String) getAttributeInternal(ATTRIBUTE10);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE10 using the alias name Attribute10.
     * @param value value to set the ATTRIBUTE10
     */
    public void setAttribute10(String value) {
        setAttributeInternal(ATTRIBUTE10, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE11 using the alias name Attribute11.
     * @return the ATTRIBUTE11
     */
    public String getAttribute11() {
        return (String) getAttributeInternal(ATTRIBUTE11);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE11 using the alias name Attribute11.
     * @param value value to set the ATTRIBUTE11
     */
    public void setAttribute11(String value) {
        setAttributeInternal(ATTRIBUTE11, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE12 using the alias name Attribute12.
     * @return the ATTRIBUTE12
     */
    public String getAttribute12() {
        return (String) getAttributeInternal(ATTRIBUTE12);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE12 using the alias name Attribute12.
     * @param value value to set the ATTRIBUTE12
     */
    public void setAttribute12(String value) {
        setAttributeInternal(ATTRIBUTE12, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE13 using the alias name Attribute13.
     * @return the ATTRIBUTE13
     */
    public String getAttribute13() {
        return (String) getAttributeInternal(ATTRIBUTE13);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE13 using the alias name Attribute13.
     * @param value value to set the ATTRIBUTE13
     */
    public void setAttribute13(String value) {
        setAttributeInternal(ATTRIBUTE13, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE14 using the alias name Attribute14.
     * @return the ATTRIBUTE14
     */
    public String getAttribute14() {
        return (String) getAttributeInternal(ATTRIBUTE14);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE14 using the alias name Attribute14.
     * @param value value to set the ATTRIBUTE14
     */
    public void setAttribute14(String value) {
        setAttributeInternal(ATTRIBUTE14, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE15 using the alias name Attribute15.
     * @return the ATTRIBUTE15
     */
    public String getAttribute15() {
        return (String) getAttributeInternal(ATTRIBUTE15);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE15 using the alias name Attribute15.
     * @param value value to set the ATTRIBUTE15
     */
    public void setAttribute15(String value) {
        setAttributeInternal(ATTRIBUTE15, value);
    }

    /**
     * Gets the attribute value for SALESORDER_ID using the alias name SalesorderId.
     * @return the SALESORDER_ID
     */
    public Number getSalesorderId() {
        return (Number) getAttributeInternal(SALESORDERID);
    }

    /**
     * Sets <code>value</code> as attribute value for SALESORDER_ID using the alias name SalesorderId.
     * @param value value to set the SALESORDER_ID
     */
    public void setSalesorderId(Number value) {
        setAttributeInternal(SALESORDERID, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @return the LAST_UPDATE_DATE
     */
    public Date getLastUpdateDate() {
        return (Date) getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @param value value to set the LAST_UPDATE_DATE
     */
    public void setLastUpdateDate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @return the LAST_UPDATED_BY
     */
    public Number getLastUpdatedBy() {
        return (Number) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @param value value to set the LAST_UPDATED_BY
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for CREATION_DATE using the alias name CreationDate.
     * @return the CREATION_DATE
     */
    public Date getCreationDate() {
        return (Date) getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATION_DATE using the alias name CreationDate.
     * @param value value to set the CREATION_DATE
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public Number getCreatedBy() {
        return (Number) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy.
     * @param value value to set the CREATED_BY
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for ORG_ID using the alias name OrgId.
     * @return the ORG_ID
     */
    public Number getOrgId() {
        return (Number) getAttributeInternal(ORGID);
    }

    /**
     * Sets <code>value</code> as attribute value for ORG_ID using the alias name OrgId.
     * @param value value to set the ORG_ID
     */
    public void setOrgId(Number value) {
        setAttributeInternal(ORGID, value);
    }

    /**
     * Gets the attribute value for CHALLAN_NO using the alias name ChallanNo.
     * @return the CHALLAN_NO
     */
    public Number getChallanNo() {
        return (Number) getAttributeInternal(CHALLANNO);
    }

    /**
     * Sets <code>value</code> as attribute value for CHALLAN_NO using the alias name ChallanNo.
     * @param value value to set the CHALLAN_NO
     */
    public void setChallanNo(Number value) {
        setAttributeInternal(CHALLANNO, value);
    }

    /**
     * Gets the attribute value for WASH_TYPE using the alias name WashType.
     * @return the WASH_TYPE
     */
    public String getWashType() {
        return (String) getAttributeInternal(WASHTYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for WASH_TYPE using the alias name WashType.
     * @param value value to set the WASH_TYPE
     */
    public void setWashType(String value) {
        setAttributeInternal(WASHTYPE, value);
    }

    /**
     * Gets the attribute value for PRODUCTION_TYPE using the alias name ProductionType.
     * @return the PRODUCTION_TYPE
     */
    public String getProductionType() {
        return (String) getAttributeInternal(PRODUCTIONTYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for PRODUCTION_TYPE using the alias name ProductionType.
     * @param value value to set the PRODUCTION_TYPE
     */
    public void setProductionType(String value) {
        setAttributeInternal(PRODUCTIONTYPE, value);
    }

    /**
     * Gets the attribute value for WASH_EMD_PRINT_INV using the alias name WashEmdPrintInv.
     * @return the WASH_EMD_PRINT_INV
     */
    public Number getWashEmdPrintInv() {
        return (Number) getAttributeInternal(WASHEMDPRINTINV);
    }

    /**
     * Sets <code>value</code> as attribute value for WASH_EMD_PRINT_INV using the alias name WashEmdPrintInv.
     * @param value value to set the WASH_EMD_PRINT_INV
     */
    public void setWashEmdPrintInv(Number value) {
        setAttributeInternal(WASHEMDPRINTINV, value);
    }

    /**
     * Gets the attribute value for ISSUANCE_DATE using the alias name IssuanceDate.
     * @return the ISSUANCE_DATE
     */
    public Date getIssuanceDate() {
        return (Date) getAttributeInternal(ISSUANCEDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for ISSUANCE_DATE using the alias name IssuanceDate.
     * @param value value to set the ISSUANCE_DATE
     */
    public void setIssuanceDate(Date value) {
        setAttributeInternal(ISSUANCEDATE, value);
    }

    /**
     * Gets the attribute value for ISSUANCE_CHALLAN_NO using the alias name IssuanceChallanNo.
     * @return the ISSUANCE_CHALLAN_NO
     */
    public String getIssuanceChallanNo() {
        return (String) getAttributeInternal(ISSUANCECHALLANNO);
    }

    /**
     * Sets <code>value</code> as attribute value for ISSUANCE_CHALLAN_NO using the alias name IssuanceChallanNo.
     * @param value value to set the ISSUANCE_CHALLAN_NO
     */
    public void setIssuanceChallanNo(String value) {
        setAttributeInternal(ISSUANCECHALLANNO, value);
    }

    /**
     * Gets the attribute value for WASH_EMD_PRINT_INVORG using the alias name WashEmdPrintInvorg.
     * @return the WASH_EMD_PRINT_INVORG
     */
    public String getWashEmdPrintInvorg() {
        return (String) getAttributeInternal(WASHEMDPRINTINVORG);
    }

    /**
     * Sets <code>value</code> as attribute value for WASH_EMD_PRINT_INVORG using the alias name WashEmdPrintInvorg.
     * @param value value to set the WASH_EMD_PRINT_INVORG
     */
    public void setWashEmdPrintInvorg(String value) {
        setAttributeInternal(WASHEMDPRINTINVORG, value);
    }

    /**
     * Gets the attribute value for the calculated attribute DeliveryDate.
     * @return the DeliveryDate
     */
    public Date getDeliveryDate() {
        return (Date) getAttributeInternal(DELIVERYDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute DeliveryDate.
     * @param value value to set the  DeliveryDate
     */
    public void setDeliveryDate(Date value) {
        setAttributeInternal(DELIVERYDATE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute BuyerId.
     * @return the BuyerId
     */
    public Number getBuyerId() {
        return (Number) getAttributeInternal(BUYERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute BuyerId.
     * @param value value to set the  BuyerId
     */
    public void setBuyerId(Number value) {
        setAttributeInternal(BUYERID, value);
    }


    /**
     * Gets the attribute value for BPO_ID using the alias name BpoId.
     * @return the BPO_ID
     */
    public Number getBpoId() {
        return (Number) getAttributeInternal(BPOID);
    }

    /**
     * Sets <code>value</code> as attribute value for BPO_ID using the alias name BpoId.
     * @param value value to set the BPO_ID
     */
    public void setBpoId(Number value) {
        setAttributeInternal(BPOID, value);
    }

    /**
     * Gets the attribute value for SYSTEM_ID using the alias name SystemId.
     * @return the SYSTEM_ID
     */
    public Number getSystemId() {
        return (Number) getAttributeInternal(SYSTEMID);
    }

    /**
     * Sets <code>value</code> as attribute value for SYSTEM_ID using the alias name SystemId.
     * @param value value to set the SYSTEM_ID
     */
    public void setSystemId(Number value) {
        setAttributeInternal(SYSTEMID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute BuyerNew.
     * @return the BuyerNew
     */
    public String getBuyerNew() {
        return (String) getAttributeInternal(BUYERNEW);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute BuyerNew.
     * @param value value to set the  BuyerNew
     */
    public void setBuyerNew(String value) {
        setAttributeInternal(BUYERNEW, value);
    }

    /**
     * Gets the attribute value for the calculated attribute SeasonNew.
     * @return the SeasonNew
     */
    public String getSeasonNew() {
        return (String) getAttributeInternal(SEASONNEW);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute SeasonNew.
     * @param value value to set the  SeasonNew
     */
    public void setSeasonNew(String value) {
        setAttributeInternal(SEASONNEW, value);
    }

    /**
     * Gets the attribute value for the calculated attribute StyleNew.
     * @return the StyleNew
     */
    public String getStyleNew() {
        return (String) getAttributeInternal(STYLENEW);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute StyleNew.
     * @param value value to set the  StyleNew
     */
    public void setStyleNew(String value) {
        setAttributeInternal(STYLENEW, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ColorNew.
     * @return the ColorNew
     */
    public String getColorNew() {
        return (String) getAttributeInternal(COLORNEW);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ColorNew.
     * @param value value to set the  ColorNew
     */
    public void setColorNew(String value) {
        setAttributeInternal(COLORNEW, value);
    }

    /**
     * Gets the attribute value for the calculated attribute WashNew.
     * @return the WashNew
     */
    public String getWashNew() {
        return (String) getAttributeInternal(WASHNEW);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute WashNew.
     * @param value value to set the  WashNew
     */
    public void setWashNew(String value) {
        setAttributeInternal(WASHNEW, value);
    }

    /**
     * Gets the attribute value for the calculated attribute BpoNew.
     * @return the BpoNew
     */
    public String getBpoNew() {
        return (String) getAttributeInternal(BPONEW);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute BpoNew.
     * @param value value to set the  BpoNew
     */
    public void setBpoNew(String value) {
        setAttributeInternal(BPONEW, value);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link MNJ_ISSUEREC_WASH_DEL_SIZE_VO.
     */
    public RowIterator getMNJ_ISSUEREC_WASH_DEL_SIZE_VO() {
        return (RowIterator)getAttributeInternal(MNJ_ISSUEREC_WASH_DEL_SIZE_VO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> FillBposVO1.
     */
    public RowSet getFillBposVO1() {
        return (RowSet)getAttributeInternal(FILLBPOSVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> WashTypeVO1.
     */
    public RowSet getWashTypeVO1() {
        return (RowSet)getAttributeInternal(WASHTYPEVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> ProductionTypeVO1.
     */
    public RowSet getProductionTypeVO1() {
        return (RowSet)getAttributeInternal(PRODUCTIONTYPEVO1);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
