package mnj.mfg.model.views;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Aug 04 12:24:24 PKT 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MNJ_ISSUEREC_WASH_REC_SIZE_VOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public MNJ_ISSUEREC_WASH_REC_SIZE_VOImpl() {
    }
}
