package mnj.mfg.model.views;

import mnj.mfg.model.entities.MNJ_ISSUEREC_WASH_REC_SIZE_EOImpl;

import oracle.jbo.RowSet;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Aug 04 12:24:24 PKT 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MNJ_ISSUEREC_WASH_REC_SIZE_VORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        LineId {
            public Object get(MNJ_ISSUEREC_WASH_REC_SIZE_VORowImpl obj) {
                return obj.getLineId();
            }

            public void put(MNJ_ISSUEREC_WASH_REC_SIZE_VORowImpl obj,
                            Object value) {
                obj.setLineId((Number)value);
            }
        }
        ,
        RecevingSizeDet {
            public Object get(MNJ_ISSUEREC_WASH_REC_SIZE_VORowImpl obj) {
                return obj.getRecevingSizeDet();
            }

            public void put(MNJ_ISSUEREC_WASH_REC_SIZE_VORowImpl obj,
                            Object value) {
                obj.setRecevingSizeDet((Number)value);
            }
        }
        ,
        Inseam {
            public Object get(MNJ_ISSUEREC_WASH_REC_SIZE_VORowImpl obj) {
                return obj.getInseam();
            }

            public void put(MNJ_ISSUEREC_WASH_REC_SIZE_VORowImpl obj,
                            Object value) {
                obj.setInseam((String)value);
            }
        }
        ,
        SizeInseam {
            public Object get(MNJ_ISSUEREC_WASH_REC_SIZE_VORowImpl obj) {
                return obj.getSizeInseam();
            }

            public void put(MNJ_ISSUEREC_WASH_REC_SIZE_VORowImpl obj,
                            Object value) {
                obj.setSizeInseam((String)value);
            }
        }
        ,
        Quantity {
            public Object get(MNJ_ISSUEREC_WASH_REC_SIZE_VORowImpl obj) {
                return obj.getQuantity();
            }

            public void put(MNJ_ISSUEREC_WASH_REC_SIZE_VORowImpl obj,
                            Object value) {
                obj.setQuantity((Number)value);
            }
        }
        ,
        Attribute1 {
            public Object get(MNJ_ISSUEREC_WASH_REC_SIZE_VORowImpl obj) {
                return obj.getAttribute1();
            }

            public void put(MNJ_ISSUEREC_WASH_REC_SIZE_VORowImpl obj,
                            Object value) {
                obj.setAttribute1((String)value);
            }
        }
        ,
        SalesorderId {
            public Object get(MNJ_ISSUEREC_WASH_REC_SIZE_VORowImpl obj) {
                return obj.getSalesorderId();
            }

            public void put(MNJ_ISSUEREC_WASH_REC_SIZE_VORowImpl obj,
                            Object value) {
                obj.setSalesorderId((Number)value);
            }
        }
        ,
        LastUpdateDate {
            public Object get(MNJ_ISSUEREC_WASH_REC_SIZE_VORowImpl obj) {
                return obj.getLastUpdateDate();
            }

            public void put(MNJ_ISSUEREC_WASH_REC_SIZE_VORowImpl obj,
                            Object value) {
                obj.setLastUpdateDate((Date)value);
            }
        }
        ,
        LastUpdatedBy {
            public Object get(MNJ_ISSUEREC_WASH_REC_SIZE_VORowImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(MNJ_ISSUEREC_WASH_REC_SIZE_VORowImpl obj,
                            Object value) {
                obj.setLastUpdatedBy((Number)value);
            }
        }
        ,
        CreationDate {
            public Object get(MNJ_ISSUEREC_WASH_REC_SIZE_VORowImpl obj) {
                return obj.getCreationDate();
            }

            public void put(MNJ_ISSUEREC_WASH_REC_SIZE_VORowImpl obj,
                            Object value) {
                obj.setCreationDate((Date)value);
            }
        }
        ,
        CreatedBy {
            public Object get(MNJ_ISSUEREC_WASH_REC_SIZE_VORowImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(MNJ_ISSUEREC_WASH_REC_SIZE_VORowImpl obj,
                            Object value) {
                obj.setCreatedBy((Number)value);
            }
        }
        ,
        OrgId {
            public Object get(MNJ_ISSUEREC_WASH_REC_SIZE_VORowImpl obj) {
                return obj.getOrgId();
            }

            public void put(MNJ_ISSUEREC_WASH_REC_SIZE_VORowImpl obj,
                            Object value) {
                obj.setOrgId((Number)value);
            }
        }
        ,
        RewashSendDate {
            public Object get(MNJ_ISSUEREC_WASH_REC_SIZE_VORowImpl obj) {
                return obj.getRewashSendDate();
            }

            public void put(MNJ_ISSUEREC_WASH_REC_SIZE_VORowImpl obj,
                            Object value) {
                obj.setRewashSendDate((Date)value);
            }
        }
        ,
        RewashSendQty {
            public Object get(MNJ_ISSUEREC_WASH_REC_SIZE_VORowImpl obj) {
                return obj.getRewashSendQty();
            }

            public void put(MNJ_ISSUEREC_WASH_REC_SIZE_VORowImpl obj,
                            Object value) {
                obj.setRewashSendQty((Number)value);
            }
        }
        ,
        RewashReceiveDate {
            public Object get(MNJ_ISSUEREC_WASH_REC_SIZE_VORowImpl obj) {
                return obj.getRewashReceiveDate();
            }

            public void put(MNJ_ISSUEREC_WASH_REC_SIZE_VORowImpl obj,
                            Object value) {
                obj.setRewashReceiveDate((Date)value);
            }
        }
        ,
        Remarks {
            public Object get(MNJ_ISSUEREC_WASH_REC_SIZE_VORowImpl obj) {
                return obj.getRemarks();
            }

            public void put(MNJ_ISSUEREC_WASH_REC_SIZE_VORowImpl obj,
                            Object value) {
                obj.setRemarks((String)value);
            }
        }
        ,
        RejectionType {
            public Object get(MNJ_ISSUEREC_WASH_REC_SIZE_VORowImpl obj) {
                return obj.getRejectionType();
            }

            public void put(MNJ_ISSUEREC_WASH_REC_SIZE_VORowImpl obj,
                            Object value) {
                obj.setRejectionType((String)value);
            }
        }
        ,
        ProblemType {
            public Object get(MNJ_ISSUEREC_WASH_REC_SIZE_VORowImpl obj) {
                return obj.getProblemType();
            }

            public void put(MNJ_ISSUEREC_WASH_REC_SIZE_VORowImpl obj,
                            Object value) {
                obj.setProblemType((String)value);
            }
        }
        ,
        StitchingWashingOne {
            public Object get(MNJ_ISSUEREC_WASH_REC_SIZE_VORowImpl obj) {
                return obj.getStitchingWashingOne();
            }

            public void put(MNJ_ISSUEREC_WASH_REC_SIZE_VORowImpl obj,
                            Object value) {
                obj.setStitchingWashingOne((String)value);
            }
        }
        ,
        StitchingWashingTwo {
            public Object get(MNJ_ISSUEREC_WASH_REC_SIZE_VORowImpl obj) {
                return obj.getStitchingWashingTwo();
            }

            public void put(MNJ_ISSUEREC_WASH_REC_SIZE_VORowImpl obj,
                            Object value) {
                obj.setStitchingWashingTwo((String)value);
            }
        }
        ,
        Stitching_Washing_LOV1 {
            public Object get(MNJ_ISSUEREC_WASH_REC_SIZE_VORowImpl obj) {
                return obj.getStitching_Washing_LOV1();
            }

            public void put(MNJ_ISSUEREC_WASH_REC_SIZE_VORowImpl obj,
                            Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Problem_Type_LOV1 {
            public Object get(MNJ_ISSUEREC_WASH_REC_SIZE_VORowImpl obj) {
                return obj.getProblem_Type_LOV1();
            }

            public void put(MNJ_ISSUEREC_WASH_REC_SIZE_VORowImpl obj,
                            Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Rejection_Type_LOV1 {
            public Object get(MNJ_ISSUEREC_WASH_REC_SIZE_VORowImpl obj) {
                return obj.getRejection_Type_LOV1();
            }

            public void put(MNJ_ISSUEREC_WASH_REC_SIZE_VORowImpl obj,
                            Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(MNJ_ISSUEREC_WASH_REC_SIZE_VORowImpl object);

        public abstract void put(MNJ_ISSUEREC_WASH_REC_SIZE_VORowImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int LINEID = AttributesEnum.LineId.index();
    public static final int RECEVINGSIZEDET = AttributesEnum.RecevingSizeDet.index();
    public static final int INSEAM = AttributesEnum.Inseam.index();
    public static final int SIZEINSEAM = AttributesEnum.SizeInseam.index();
    public static final int QUANTITY = AttributesEnum.Quantity.index();
    public static final int ATTRIBUTE1 = AttributesEnum.Attribute1.index();
    public static final int SALESORDERID = AttributesEnum.SalesorderId.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int ORGID = AttributesEnum.OrgId.index();
    public static final int REWASHSENDDATE = AttributesEnum.RewashSendDate.index();
    public static final int REWASHSENDQTY = AttributesEnum.RewashSendQty.index();
    public static final int REWASHRECEIVEDATE = AttributesEnum.RewashReceiveDate.index();
    public static final int REMARKS = AttributesEnum.Remarks.index();
    public static final int REJECTIONTYPE = AttributesEnum.RejectionType.index();
    public static final int PROBLEMTYPE = AttributesEnum.ProblemType.index();
    public static final int STITCHINGWASHINGONE = AttributesEnum.StitchingWashingOne.index();
    public static final int STITCHINGWASHINGTWO = AttributesEnum.StitchingWashingTwo.index();
    public static final int STITCHING_WASHING_LOV1 = AttributesEnum.Stitching_Washing_LOV1.index();
    public static final int PROBLEM_TYPE_LOV1 = AttributesEnum.Problem_Type_LOV1.index();
    public static final int REJECTION_TYPE_LOV1 = AttributesEnum.Rejection_Type_LOV1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public MNJ_ISSUEREC_WASH_REC_SIZE_VORowImpl() {
    }

    /**
     * Gets MNJ_ISSUEREC_WASH_REC_SIZE_E1 entity object.
     * @return the MNJ_ISSUEREC_WASH_REC_SIZE_E1
     */
    public MNJ_ISSUEREC_WASH_REC_SIZE_EOImpl getMNJ_ISSUEREC_WASH_REC_SIZE_E1() {
        return (MNJ_ISSUEREC_WASH_REC_SIZE_EOImpl)getEntity(0);
    }

    /**
     * Gets the attribute value for LINE_ID using the alias name LineId.
     * @return the LINE_ID
     */
    public Number getLineId() {
        return (Number) getAttributeInternal(LINEID);
    }

    /**
     * Sets <code>value</code> as attribute value for LINE_ID using the alias name LineId.
     * @param value value to set the LINE_ID
     */
    public void setLineId(Number value) {
        setAttributeInternal(LINEID, value);
    }

    /**
     * Gets the attribute value for RECEVING_SIZE_DET using the alias name RecevingSizeDet.
     * @return the RECEVING_SIZE_DET
     */
    public Number getRecevingSizeDet() {
        return (Number) getAttributeInternal(RECEVINGSIZEDET);
    }

    /**
     * Sets <code>value</code> as attribute value for RECEVING_SIZE_DET using the alias name RecevingSizeDet.
     * @param value value to set the RECEVING_SIZE_DET
     */
    public void setRecevingSizeDet(Number value) {
        setAttributeInternal(RECEVINGSIZEDET, value);
    }

    /**
     * Gets the attribute value for INSEAM using the alias name Inseam.
     * @return the INSEAM
     */
    public String getInseam() {
        return (String) getAttributeInternal(INSEAM);
    }

    /**
     * Sets <code>value</code> as attribute value for INSEAM using the alias name Inseam.
     * @param value value to set the INSEAM
     */
    public void setInseam(String value) {
        setAttributeInternal(INSEAM, value);
    }

    /**
     * Gets the attribute value for SIZE_INSEAM using the alias name SizeInseam.
     * @return the SIZE_INSEAM
     */
    public String getSizeInseam() {
        return (String) getAttributeInternal(SIZEINSEAM);
    }

    /**
     * Sets <code>value</code> as attribute value for SIZE_INSEAM using the alias name SizeInseam.
     * @param value value to set the SIZE_INSEAM
     */
    public void setSizeInseam(String value) {
        setAttributeInternal(SIZEINSEAM, value);
    }

    /**
     * Gets the attribute value for QUANTITY using the alias name Quantity.
     * @return the QUANTITY
     */
    public Number getQuantity() {
        return (Number) getAttributeInternal(QUANTITY);
    }

    /**
     * Sets <code>value</code> as attribute value for QUANTITY using the alias name Quantity.
     * @param value value to set the QUANTITY
     */
    public void setQuantity(Number value) {
        setAttributeInternal(QUANTITY, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE1 using the alias name Attribute1.
     * @return the ATTRIBUTE1
     */
    public String getAttribute1() {
        return (String) getAttributeInternal(ATTRIBUTE1);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE1 using the alias name Attribute1.
     * @param value value to set the ATTRIBUTE1
     */
    public void setAttribute1(String value) {
        setAttributeInternal(ATTRIBUTE1, value);
    }

    /**
     * Gets the attribute value for SALESORDER_ID using the alias name SalesorderId.
     * @return the SALESORDER_ID
     */
    public Number getSalesorderId() {
        return (Number) getAttributeInternal(SALESORDERID);
    }

    /**
     * Sets <code>value</code> as attribute value for SALESORDER_ID using the alias name SalesorderId.
     * @param value value to set the SALESORDER_ID
     */
    public void setSalesorderId(Number value) {
        setAttributeInternal(SALESORDERID, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @return the LAST_UPDATE_DATE
     */
    public Date getLastUpdateDate() {
        return (Date) getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @param value value to set the LAST_UPDATE_DATE
     */
    public void setLastUpdateDate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @return the LAST_UPDATED_BY
     */
    public Number getLastUpdatedBy() {
        return (Number) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @param value value to set the LAST_UPDATED_BY
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for CREATION_DATE using the alias name CreationDate.
     * @return the CREATION_DATE
     */
    public Date getCreationDate() {
        return (Date) getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATION_DATE using the alias name CreationDate.
     * @param value value to set the CREATION_DATE
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public Number getCreatedBy() {
        return (Number) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy.
     * @param value value to set the CREATED_BY
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for ORG_ID using the alias name OrgId.
     * @return the ORG_ID
     */
    public Number getOrgId() {
        return (Number) getAttributeInternal(ORGID);
    }

    /**
     * Sets <code>value</code> as attribute value for ORG_ID using the alias name OrgId.
     * @param value value to set the ORG_ID
     */
    public void setOrgId(Number value) {
        setAttributeInternal(ORGID, value);
    }

    /**
     * Gets the attribute value for REWASH_SEND_DATE using the alias name RewashSendDate.
     * @return the REWASH_SEND_DATE
     */
    public Date getRewashSendDate() {
        return (Date) getAttributeInternal(REWASHSENDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for REWASH_SEND_DATE using the alias name RewashSendDate.
     * @param value value to set the REWASH_SEND_DATE
     */
    public void setRewashSendDate(Date value) {
        setAttributeInternal(REWASHSENDDATE, value);
    }

    /**
     * Gets the attribute value for REWASH_SEND_QTY using the alias name RewashSendQty.
     * @return the REWASH_SEND_QTY
     */
    public Number getRewashSendQty() {
        return (Number) getAttributeInternal(REWASHSENDQTY);
    }

    /**
     * Sets <code>value</code> as attribute value for REWASH_SEND_QTY using the alias name RewashSendQty.
     * @param value value to set the REWASH_SEND_QTY
     */
    public void setRewashSendQty(Number value) {
        setAttributeInternal(REWASHSENDQTY, value);
    }

    /**
     * Gets the attribute value for REWASH_RECEIVE_DATE using the alias name RewashReceiveDate.
     * @return the REWASH_RECEIVE_DATE
     */
    public Date getRewashReceiveDate() {
        return (Date) getAttributeInternal(REWASHRECEIVEDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for REWASH_RECEIVE_DATE using the alias name RewashReceiveDate.
     * @param value value to set the REWASH_RECEIVE_DATE
     */
    public void setRewashReceiveDate(Date value) {
        setAttributeInternal(REWASHRECEIVEDATE, value);
    }

    /**
     * Gets the attribute value for REMARKS using the alias name Remarks.
     * @return the REMARKS
     */
    public String getRemarks() {
        return (String) getAttributeInternal(REMARKS);
    }

    /**
     * Sets <code>value</code> as attribute value for REMARKS using the alias name Remarks.
     * @param value value to set the REMARKS
     */
    public void setRemarks(String value) {
        setAttributeInternal(REMARKS, value);
    }

    /**
     * Gets the attribute value for REJECTION_TYPE using the alias name RejectionType.
     * @return the REJECTION_TYPE
     */
    public String getRejectionType() {
        return (String) getAttributeInternal(REJECTIONTYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for REJECTION_TYPE using the alias name RejectionType.
     * @param value value to set the REJECTION_TYPE
     */
    public void setRejectionType(String value) {
        setAttributeInternal(REJECTIONTYPE, value);
    }

    /**
     * Gets the attribute value for PROBLEM_TYPE using the alias name ProblemType.
     * @return the PROBLEM_TYPE
     */
    public String getProblemType() {
        return (String) getAttributeInternal(PROBLEMTYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for PROBLEM_TYPE using the alias name ProblemType.
     * @param value value to set the PROBLEM_TYPE
     */
    public void setProblemType(String value) {
        setAttributeInternal(PROBLEMTYPE, value);
    }

    /**
     * Gets the attribute value for STITCHING_WASHING_ONE using the alias name StitchingWashingOne.
     * @return the STITCHING_WASHING_ONE
     */
    public String getStitchingWashingOne() {
        return (String) getAttributeInternal(STITCHINGWASHINGONE);
    }

    /**
     * Sets <code>value</code> as attribute value for STITCHING_WASHING_ONE using the alias name StitchingWashingOne.
     * @param value value to set the STITCHING_WASHING_ONE
     */
    public void setStitchingWashingOne(String value) {
        setAttributeInternal(STITCHINGWASHINGONE, value);
    }

    /**
     * Gets the attribute value for STITCHING_WASHING_TWO using the alias name StitchingWashingTwo.
     * @return the STITCHING_WASHING_TWO
     */
    public String getStitchingWashingTwo() {
        return (String) getAttributeInternal(STITCHINGWASHINGTWO);
    }

    /**
     * Sets <code>value</code> as attribute value for STITCHING_WASHING_TWO using the alias name StitchingWashingTwo.
     * @param value value to set the STITCHING_WASHING_TWO
     */
    public void setStitchingWashingTwo(String value) {
        setAttributeInternal(STITCHINGWASHINGTWO, value);
    }

    /**
     * Gets the view accessor <code>RowSet</code> Stitching_Washing_LOV1.
     */
    public RowSet getStitching_Washing_LOV1() {
        return (RowSet)getAttributeInternal(STITCHING_WASHING_LOV1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> Problem_Type_LOV1.
     */
    public RowSet getProblem_Type_LOV1() {
        return (RowSet)getAttributeInternal(PROBLEM_TYPE_LOV1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> Rejection_Type_LOV1.
     */
    public RowSet getRejection_Type_LOV1() {
        return (RowSet)getAttributeInternal(REJECTION_TYPE_LOV1);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
