package mnj.mfg.model.lov;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue May 03 17:48:37 PKT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class FillBposVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public FillBposVOImpl() {
    }


    /**
     * Returns the bind variable value for P_RESP_ID.
     * @return bind variable value for P_RESP_ID
     */
    public String getP_RESP_ID() {
        return (String)getNamedWhereClauseParam("P_RESP_ID");
    }

    /**
     * Sets <code>value</code> for bind variable P_RESP_ID.
     * @param value value to bind as P_RESP_ID
     */
    public void setP_RESP_ID(String value) {
        setNamedWhereClauseParam("P_RESP_ID", value);
    }
}
