package mnj.mfg.model.lov;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Aug 07 12:05:15 BDT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class InvOrgVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public InvOrgVOImpl() {
    }
}
