package mnj.mfg.model.lov;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Sep 26 17:48:43 BDT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class operatingUnitsVoImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public operatingUnitsVoImpl() {
    }
}
