package mnj.mfg.model.lov;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue May 03 18:05:23 PKT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class papulateSizeVoImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public papulateSizeVoImpl() {
    }


}
