package mnj.mfg.model.lov;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed May 04 14:34:24 PKT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class similarPopSizeVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public similarPopSizeVOImpl() {
    }


}
