package mnj.mfg.model.lov;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue May 03 16:41:51 PKT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class styleImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public styleImpl() {
    }

    /**
     * Returns the bind variable value for p_buyerId.
     * @return bind variable value for p_buyerId
     */
    public String getp_buyerId() {
        return (String)getNamedWhereClauseParam("p_buyerId");
    }

    /**
     * Sets <code>value</code> for bind variable p_buyerId.
     * @param value value to bind as p_buyerId
     */
    public void setp_buyerId(String value) {
        setNamedWhereClauseParam("p_buyerId", value);
    }
}
