package mnj.mfg.model.entities;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon May 02 18:10:12 PKT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class IssueInseemSizeDEOImpl extends EntityImpl {
    private static EntityDefImpl mDefinitionObject;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        HeaderId {
            public Object get(IssueInseemSizeDEOImpl obj) {
                return obj.getHeaderId();
            }

            public void put(IssueInseemSizeDEOImpl obj, Object value) {
                obj.setHeaderId((Number)value);
            }
        }
        ,
        LineId {
            public Object get(IssueInseemSizeDEOImpl obj) {
                return obj.getLineId();
            }

            public void put(IssueInseemSizeDEOImpl obj, Object value) {
                obj.setLineId((Number)value);
            }
        }
        ,
        SizeDetail {
            public Object get(IssueInseemSizeDEOImpl obj) {
                return obj.getSizeDetail();
            }

            public void put(IssueInseemSizeDEOImpl obj, Object value) {
                obj.setSizeDetail((Number)value);
            }
        }
        ,
        Inseam {
            public Object get(IssueInseemSizeDEOImpl obj) {
                return obj.getInseam();
            }

            public void put(IssueInseemSizeDEOImpl obj, Object value) {
                obj.setInseam((String)value);
            }
        }
        ,
        SizeInseam {
            public Object get(IssueInseemSizeDEOImpl obj) {
                return obj.getSizeInseam();
            }

            public void put(IssueInseemSizeDEOImpl obj, Object value) {
                obj.setSizeInseam((String)value);
            }
        }
        ,
        Quantity {
            public Object get(IssueInseemSizeDEOImpl obj) {
                return obj.getQuantity();
            }

            public void put(IssueInseemSizeDEOImpl obj, Object value) {
                obj.setQuantity((Number)value);
            }
        }
        ,
        Attribute1 {
            public Object get(IssueInseemSizeDEOImpl obj) {
                return obj.getAttribute1();
            }

            public void put(IssueInseemSizeDEOImpl obj, Object value) {
                obj.setAttribute1((String)value);
            }
        }
        ,
        Attribute2 {
            public Object get(IssueInseemSizeDEOImpl obj) {
                return obj.getAttribute2();
            }

            public void put(IssueInseemSizeDEOImpl obj, Object value) {
                obj.setAttribute2((String)value);
            }
        }
        ,
        Attribute3 {
            public Object get(IssueInseemSizeDEOImpl obj) {
                return obj.getAttribute3();
            }

            public void put(IssueInseemSizeDEOImpl obj, Object value) {
                obj.setAttribute3((String)value);
            }
        }
        ,
        Attribute4 {
            public Object get(IssueInseemSizeDEOImpl obj) {
                return obj.getAttribute4();
            }

            public void put(IssueInseemSizeDEOImpl obj, Object value) {
                obj.setAttribute4((String)value);
            }
        }
        ,
        Attribute5 {
            public Object get(IssueInseemSizeDEOImpl obj) {
                return obj.getAttribute5();
            }

            public void put(IssueInseemSizeDEOImpl obj, Object value) {
                obj.setAttribute5((String)value);
            }
        }
        ,
        Attribute6 {
            public Object get(IssueInseemSizeDEOImpl obj) {
                return obj.getAttribute6();
            }

            public void put(IssueInseemSizeDEOImpl obj, Object value) {
                obj.setAttribute6((String)value);
            }
        }
        ,
        Attribute7 {
            public Object get(IssueInseemSizeDEOImpl obj) {
                return obj.getAttribute7();
            }

            public void put(IssueInseemSizeDEOImpl obj, Object value) {
                obj.setAttribute7((String)value);
            }
        }
        ,
        Attribute8 {
            public Object get(IssueInseemSizeDEOImpl obj) {
                return obj.getAttribute8();
            }

            public void put(IssueInseemSizeDEOImpl obj, Object value) {
                obj.setAttribute8((String)value);
            }
        }
        ,
        Attribute9 {
            public Object get(IssueInseemSizeDEOImpl obj) {
                return obj.getAttribute9();
            }

            public void put(IssueInseemSizeDEOImpl obj, Object value) {
                obj.setAttribute9((String)value);
            }
        }
        ,
        Attribute10 {
            public Object get(IssueInseemSizeDEOImpl obj) {
                return obj.getAttribute10();
            }

            public void put(IssueInseemSizeDEOImpl obj, Object value) {
                obj.setAttribute10((String)value);
            }
        }
        ,
        Attribute11 {
            public Object get(IssueInseemSizeDEOImpl obj) {
                return obj.getAttribute11();
            }

            public void put(IssueInseemSizeDEOImpl obj, Object value) {
                obj.setAttribute11((String)value);
            }
        }
        ,
        Attribute12 {
            public Object get(IssueInseemSizeDEOImpl obj) {
                return obj.getAttribute12();
            }

            public void put(IssueInseemSizeDEOImpl obj, Object value) {
                obj.setAttribute12((String)value);
            }
        }
        ,
        Attribute13 {
            public Object get(IssueInseemSizeDEOImpl obj) {
                return obj.getAttribute13();
            }

            public void put(IssueInseemSizeDEOImpl obj, Object value) {
                obj.setAttribute13((String)value);
            }
        }
        ,
        Attribute14 {
            public Object get(IssueInseemSizeDEOImpl obj) {
                return obj.getAttribute14();
            }

            public void put(IssueInseemSizeDEOImpl obj, Object value) {
                obj.setAttribute14((String)value);
            }
        }
        ,
        Attribute15 {
            public Object get(IssueInseemSizeDEOImpl obj) {
                return obj.getAttribute15();
            }

            public void put(IssueInseemSizeDEOImpl obj, Object value) {
                obj.setAttribute15((String)value);
            }
        }
        ,
        SalesorderId {
            public Object get(IssueInseemSizeDEOImpl obj) {
                return obj.getSalesorderId();
            }

            public void put(IssueInseemSizeDEOImpl obj, Object value) {
                obj.setSalesorderId((Number)value);
            }
        }
        ,
        LastUpdateDate {
            public Object get(IssueInseemSizeDEOImpl obj) {
                return obj.getLastUpdateDate();
            }

            public void put(IssueInseemSizeDEOImpl obj, Object value) {
                obj.setLastUpdateDate((Date)value);
            }
        }
        ,
        LastUpdatedBy {
            public Object get(IssueInseemSizeDEOImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(IssueInseemSizeDEOImpl obj, Object value) {
                obj.setLastUpdatedBy((Number)value);
            }
        }
        ,
        CreationDate {
            public Object get(IssueInseemSizeDEOImpl obj) {
                return obj.getCreationDate();
            }

            public void put(IssueInseemSizeDEOImpl obj, Object value) {
                obj.setCreationDate((Date)value);
            }
        }
        ,
        CreatedBy {
            public Object get(IssueInseemSizeDEOImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(IssueInseemSizeDEOImpl obj, Object value) {
                obj.setCreatedBy((Number)value);
            }
        }
        ,
        OrgId {
            public Object get(IssueInseemSizeDEOImpl obj) {
                return obj.getOrgId();
            }

            public void put(IssueInseemSizeDEOImpl obj, Object value) {
                obj.setOrgId((Number)value);
            }
        }
        ,
        Remarks {
            public Object get(IssueInseemSizeDEOImpl obj) {
                return obj.getRemarks();
            }

            public void put(IssueInseemSizeDEOImpl obj, Object value) {
                obj.setRemarks((String)value);
            }
        }
        ,
        ProblemType {
            public Object get(IssueInseemSizeDEOImpl obj) {
                return obj.getProblemType();
            }

            public void put(IssueInseemSizeDEOImpl obj, Object value) {
                obj.setProblemType((String)value);
            }
        }
        ,
        RejectionType {
            public Object get(IssueInseemSizeDEOImpl obj) {
                return obj.getRejectionType();
            }

            public void put(IssueInseemSizeDEOImpl obj, Object value) {
                obj.setRejectionType((String)value);
            }
        }
        ,
        StitchingWashingOne {
            public Object get(IssueInseemSizeDEOImpl obj) {
                return obj.getStitchingWashingOne();
            }

            public void put(IssueInseemSizeDEOImpl obj, Object value) {
                obj.setStitchingWashingOne((String)value);
            }
        }
        ,
        StitchingWashingTwo {
            public Object get(IssueInseemSizeDEOImpl obj) {
                return obj.getStitchingWashingTwo();
            }

            public void put(IssueInseemSizeDEOImpl obj, Object value) {
                obj.setStitchingWashingTwo((String)value);
            }
        }
        ,
        LineEO {
            public Object get(IssueInseemSizeDEOImpl obj) {
                return obj.getLineEO();
            }

            public void put(IssueInseemSizeDEOImpl obj, Object value) {
                obj.setLineEO((LineEOImpl)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(IssueInseemSizeDEOImpl object);

        public abstract void put(IssueInseemSizeDEOImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int HEADERID = AttributesEnum.HeaderId.index();
    public static final int LINEID = AttributesEnum.LineId.index();
    public static final int SIZEDETAIL = AttributesEnum.SizeDetail.index();
    public static final int INSEAM = AttributesEnum.Inseam.index();
    public static final int SIZEINSEAM = AttributesEnum.SizeInseam.index();
    public static final int QUANTITY = AttributesEnum.Quantity.index();
    public static final int ATTRIBUTE1 = AttributesEnum.Attribute1.index();
    public static final int ATTRIBUTE2 = AttributesEnum.Attribute2.index();
    public static final int ATTRIBUTE3 = AttributesEnum.Attribute3.index();
    public static final int ATTRIBUTE4 = AttributesEnum.Attribute4.index();
    public static final int ATTRIBUTE5 = AttributesEnum.Attribute5.index();
    public static final int ATTRIBUTE6 = AttributesEnum.Attribute6.index();
    public static final int ATTRIBUTE7 = AttributesEnum.Attribute7.index();
    public static final int ATTRIBUTE8 = AttributesEnum.Attribute8.index();
    public static final int ATTRIBUTE9 = AttributesEnum.Attribute9.index();
    public static final int ATTRIBUTE10 = AttributesEnum.Attribute10.index();
    public static final int ATTRIBUTE11 = AttributesEnum.Attribute11.index();
    public static final int ATTRIBUTE12 = AttributesEnum.Attribute12.index();
    public static final int ATTRIBUTE13 = AttributesEnum.Attribute13.index();
    public static final int ATTRIBUTE14 = AttributesEnum.Attribute14.index();
    public static final int ATTRIBUTE15 = AttributesEnum.Attribute15.index();
    public static final int SALESORDERID = AttributesEnum.SalesorderId.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int ORGID = AttributesEnum.OrgId.index();
    public static final int REMARKS = AttributesEnum.Remarks.index();
    public static final int PROBLEMTYPE = AttributesEnum.ProblemType.index();
    public static final int REJECTIONTYPE = AttributesEnum.RejectionType.index();
    public static final int STITCHINGWASHINGONE = AttributesEnum.StitchingWashingOne.index();
    public static final int STITCHINGWASHINGTWO = AttributesEnum.StitchingWashingTwo.index();
    public static final int LINEEO = AttributesEnum.LineEO.index();

    /**
     * This is the default constructor (do not remove).
     */
    public IssueInseemSizeDEOImpl() {
    }


    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = EntityDefImpl.findDefObject("mnj.mfg.model.entities.IssueInseemSizeDEO");
        }
        return mDefinitionObject;
    }

    /**
     * Gets the attribute value for HeaderId, using the alias name HeaderId.
     * @return the HeaderId
     */
    public Number getHeaderId() {
        return (Number)getAttributeInternal(HEADERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for HeaderId.
     * @param value value to set the HeaderId
     */
    public void setHeaderId(Number value) {
        setAttributeInternal(HEADERID, value);
    }

    /**
     * Gets the attribute value for LineId, using the alias name LineId.
     * @return the LineId
     */
    public Number getLineId() {
        return (Number)getAttributeInternal(LINEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for LineId.
     * @param value value to set the LineId
     */
    public void setLineId(Number value) {
        setAttributeInternal(LINEID, value);
    }

    /**
     * Gets the attribute value for SizeDetail, using the alias name SizeDetail.
     * @return the SizeDetail
     */
    public Number getSizeDetail() {
        return (Number)getAttributeInternal(SIZEDETAIL);
    }

    /**
     * Sets <code>value</code> as the attribute value for SizeDetail.
     * @param value value to set the SizeDetail
     */
    public void setSizeDetail(Number value) {
        setAttributeInternal(SIZEDETAIL, value);
    }

    /**
     * Gets the attribute value for Inseam, using the alias name Inseam.
     * @return the Inseam
     */
    public String getInseam() {
        return (String)getAttributeInternal(INSEAM);
    }

    /**
     * Sets <code>value</code> as the attribute value for Inseam.
     * @param value value to set the Inseam
     */
    public void setInseam(String value) {
        setAttributeInternal(INSEAM, value);
    }

    /**
     * Gets the attribute value for SizeInseam, using the alias name SizeInseam.
     * @return the SizeInseam
     */
    public String getSizeInseam() {
        return (String)getAttributeInternal(SIZEINSEAM);
    }

    /**
     * Sets <code>value</code> as the attribute value for SizeInseam.
     * @param value value to set the SizeInseam
     */
    public void setSizeInseam(String value) {
        setAttributeInternal(SIZEINSEAM, value);
    }

    /**
     * Gets the attribute value for Quantity, using the alias name Quantity.
     * @return the Quantity
     */
    public Number getQuantity() {
        return (Number)getAttributeInternal(QUANTITY);
    }

    /**
     * Sets <code>value</code> as the attribute value for Quantity.
     * @param value value to set the Quantity
     */
    public void setQuantity(Number value) {
        setAttributeInternal(QUANTITY, value);
    }

    /**
     * Gets the attribute value for Attribute1, using the alias name Attribute1.
     * @return the Attribute1
     */
    public String getAttribute1() {
        return (String)getAttributeInternal(ATTRIBUTE1);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute1.
     * @param value value to set the Attribute1
     */
    public void setAttribute1(String value) {
        setAttributeInternal(ATTRIBUTE1, value);
    }

    /**
     * Gets the attribute value for Attribute2, using the alias name Attribute2.
     * @return the Attribute2
     */
    public String getAttribute2() {
        return (String)getAttributeInternal(ATTRIBUTE2);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute2.
     * @param value value to set the Attribute2
     */
    public void setAttribute2(String value) {
        setAttributeInternal(ATTRIBUTE2, value);
    }

    /**
     * Gets the attribute value for Attribute3, using the alias name Attribute3.
     * @return the Attribute3
     */
    public String getAttribute3() {
        return (String)getAttributeInternal(ATTRIBUTE3);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute3.
     * @param value value to set the Attribute3
     */
    public void setAttribute3(String value) {
        setAttributeInternal(ATTRIBUTE3, value);
    }

    /**
     * Gets the attribute value for Attribute4, using the alias name Attribute4.
     * @return the Attribute4
     */
    public String getAttribute4() {
        return (String)getAttributeInternal(ATTRIBUTE4);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute4.
     * @param value value to set the Attribute4
     */
    public void setAttribute4(String value) {
        setAttributeInternal(ATTRIBUTE4, value);
    }

    /**
     * Gets the attribute value for Attribute5, using the alias name Attribute5.
     * @return the Attribute5
     */
    public String getAttribute5() {
        return (String)getAttributeInternal(ATTRIBUTE5);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute5.
     * @param value value to set the Attribute5
     */
    public void setAttribute5(String value) {
        setAttributeInternal(ATTRIBUTE5, value);
    }

    /**
     * Gets the attribute value for Attribute6, using the alias name Attribute6.
     * @return the Attribute6
     */
    public String getAttribute6() {
        return (String)getAttributeInternal(ATTRIBUTE6);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute6.
     * @param value value to set the Attribute6
     */
    public void setAttribute6(String value) {
        setAttributeInternal(ATTRIBUTE6, value);
    }

    /**
     * Gets the attribute value for Attribute7, using the alias name Attribute7.
     * @return the Attribute7
     */
    public String getAttribute7() {
        return (String)getAttributeInternal(ATTRIBUTE7);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute7.
     * @param value value to set the Attribute7
     */
    public void setAttribute7(String value) {
        setAttributeInternal(ATTRIBUTE7, value);
    }

    /**
     * Gets the attribute value for Attribute8, using the alias name Attribute8.
     * @return the Attribute8
     */
    public String getAttribute8() {
        return (String)getAttributeInternal(ATTRIBUTE8);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute8.
     * @param value value to set the Attribute8
     */
    public void setAttribute8(String value) {
        setAttributeInternal(ATTRIBUTE8, value);
    }

    /**
     * Gets the attribute value for Attribute9, using the alias name Attribute9.
     * @return the Attribute9
     */
    public String getAttribute9() {
        return (String)getAttributeInternal(ATTRIBUTE9);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute9.
     * @param value value to set the Attribute9
     */
    public void setAttribute9(String value) {
        setAttributeInternal(ATTRIBUTE9, value);
    }

    /**
     * Gets the attribute value for Attribute10, using the alias name Attribute10.
     * @return the Attribute10
     */
    public String getAttribute10() {
        return (String)getAttributeInternal(ATTRIBUTE10);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute10.
     * @param value value to set the Attribute10
     */
    public void setAttribute10(String value) {
        setAttributeInternal(ATTRIBUTE10, value);
    }

    /**
     * Gets the attribute value for Attribute11, using the alias name Attribute11.
     * @return the Attribute11
     */
    public String getAttribute11() {
        return (String)getAttributeInternal(ATTRIBUTE11);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute11.
     * @param value value to set the Attribute11
     */
    public void setAttribute11(String value) {
        setAttributeInternal(ATTRIBUTE11, value);
    }

    /**
     * Gets the attribute value for Attribute12, using the alias name Attribute12.
     * @return the Attribute12
     */
    public String getAttribute12() {
        return (String)getAttributeInternal(ATTRIBUTE12);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute12.
     * @param value value to set the Attribute12
     */
    public void setAttribute12(String value) {
        setAttributeInternal(ATTRIBUTE12, value);
    }

    /**
     * Gets the attribute value for Attribute13, using the alias name Attribute13.
     * @return the Attribute13
     */
    public String getAttribute13() {
        return (String)getAttributeInternal(ATTRIBUTE13);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute13.
     * @param value value to set the Attribute13
     */
    public void setAttribute13(String value) {
        setAttributeInternal(ATTRIBUTE13, value);
    }

    /**
     * Gets the attribute value for Attribute14, using the alias name Attribute14.
     * @return the Attribute14
     */
    public String getAttribute14() {
        return (String)getAttributeInternal(ATTRIBUTE14);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute14.
     * @param value value to set the Attribute14
     */
    public void setAttribute14(String value) {
        setAttributeInternal(ATTRIBUTE14, value);
    }

    /**
     * Gets the attribute value for Attribute15, using the alias name Attribute15.
     * @return the Attribute15
     */
    public String getAttribute15() {
        return (String)getAttributeInternal(ATTRIBUTE15);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute15.
     * @param value value to set the Attribute15
     */
    public void setAttribute15(String value) {
        setAttributeInternal(ATTRIBUTE15, value);
    }

    /**
     * Gets the attribute value for SalesorderId, using the alias name SalesorderId.
     * @return the SalesorderId
     */
    public Number getSalesorderId() {
        return (Number)getAttributeInternal(SALESORDERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for SalesorderId.
     * @param value value to set the SalesorderId
     */
    public void setSalesorderId(Number value) {
        setAttributeInternal(SALESORDERID, value);
    }

    /**
     * Gets the attribute value for LastUpdateDate, using the alias name LastUpdateDate.
     * @return the LastUpdateDate
     */
    public Date getLastUpdateDate() {
        return (Date)getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdateDate.
     * @param value value to set the LastUpdateDate
     */
    public void setLastUpdateDate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**
     * Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy.
     * @return the LastUpdatedBy
     */
    public Number getLastUpdatedBy() {
        return (Number)getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdatedBy.
     * @param value value to set the LastUpdatedBy
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for CreationDate, using the alias name CreationDate.
     * @return the CreationDate
     */
    public Date getCreationDate() {
        return (Date)getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreationDate.
     * @param value value to set the CreationDate
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the CreatedBy
     */
    public Number getCreatedBy() {
        return (Number)getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for OrgId, using the alias name OrgId.
     * @return the OrgId
     */
    public Number getOrgId() {
        return (Number)getAttributeInternal(ORGID);
    }

    /**
     * Sets <code>value</code> as the attribute value for OrgId.
     * @param value value to set the OrgId
     */
    public void setOrgId(Number value) {
        setAttributeInternal(ORGID, value);
    }

    /**
     * Gets the attribute value for Remarks, using the alias name Remarks.
     * @return the Remarks
     */
    public String getRemarks() {
        return (String)getAttributeInternal(REMARKS);
    }

    /**
     * Sets <code>value</code> as the attribute value for Remarks.
     * @param value value to set the Remarks
     */
    public void setRemarks(String value) {
        setAttributeInternal(REMARKS, value);
    }

    /**
     * Gets the attribute value for ProblemType, using the alias name ProblemType.
     * @return the ProblemType
     */
    public String getProblemType() {
        return (String)getAttributeInternal(PROBLEMTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ProblemType.
     * @param value value to set the ProblemType
     */
    public void setProblemType(String value) {
        setAttributeInternal(PROBLEMTYPE, value);
    }

    /**
     * Gets the attribute value for RejectionType, using the alias name RejectionType.
     * @return the RejectionType
     */
    public String getRejectionType() {
        return (String)getAttributeInternal(REJECTIONTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for RejectionType.
     * @param value value to set the RejectionType
     */
    public void setRejectionType(String value) {
        setAttributeInternal(REJECTIONTYPE, value);
    }

    /**
     * Gets the attribute value for StitchingWashingOne, using the alias name StitchingWashingOne.
     * @return the StitchingWashingOne
     */
    public String getStitchingWashingOne() {
        return (String)getAttributeInternal(STITCHINGWASHINGONE);
    }

    /**
     * Sets <code>value</code> as the attribute value for StitchingWashingOne.
     * @param value value to set the StitchingWashingOne
     */
    public void setStitchingWashingOne(String value) {
        setAttributeInternal(STITCHINGWASHINGONE, value);
    }

    /**
     * Gets the attribute value for StitchingWashingTwo, using the alias name StitchingWashingTwo.
     * @return the StitchingWashingTwo
     */
    public String getStitchingWashingTwo() {
        return (String)getAttributeInternal(STITCHINGWASHINGTWO);
    }

    /**
     * Sets <code>value</code> as the attribute value for StitchingWashingTwo.
     * @param value value to set the StitchingWashingTwo
     */
    public void setStitchingWashingTwo(String value) {
        setAttributeInternal(STITCHINGWASHINGTWO, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }

    /**
     * @return the associated entity LineEOImpl.
     */
    public LineEOImpl getLineEO() {
        return (LineEOImpl)getAttributeInternal(LINEEO);
    }

    /**
     * Sets <code>value</code> as the associated entity LineEOImpl.
     */
    public void setLineEO(LineEOImpl value) {
        setAttributeInternal(LINEEO, value);
    }


    /**
     * @param sizeDetail key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Number sizeDetail) {
        return new Key(new Object[]{sizeDetail});
    }

    protected void create(AttributeList attributeList) {
        super.create(attributeList);
        oracle.jbo.server.SequenceImpl s =new oracle.jbo.server.SequenceImpl("MNJ_MFG_ISSUE_INSEAM_SIZE_D_S",getDBTransaction());
        oracle.jbo.domain.Number sVal = s.getSequenceNumber();
        setSizeDetail(sVal);
    }


}
