package mnj.mfg.model.entities;

import java.sql.SQLException;

import java.util.Map;

import oracle.adf.share.ADFContext;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.RowIterator;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jan 16 14:28:37 PKT 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MNJ_ISSUE_REC_WASH_REC_L_EOImpl extends EntityImpl {
    private static EntityDefImpl mDefinitionObject;

    /**
     * Add entity remove logic in this method.
     */
    public void remove() {
        super.remove();
    }

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        HeaderId {
            public Object get(MNJ_ISSUE_REC_WASH_REC_L_EOImpl obj) {
                return obj.getHeaderId();
            }

            public void put(MNJ_ISSUE_REC_WASH_REC_L_EOImpl obj,
                            Object value) {
                obj.setHeaderId((Number)value);
            }
        }
        ,
        LineId {
            public Object get(MNJ_ISSUE_REC_WASH_REC_L_EOImpl obj) {
                return obj.getLineId();
            }

            public void put(MNJ_ISSUE_REC_WASH_REC_L_EOImpl obj,
                            Object value) {
                obj.setLineId((Number)value);
            }
        }
        ,
        RecevingChallanNo {
            public Object get(MNJ_ISSUE_REC_WASH_REC_L_EOImpl obj) {
                return obj.getRecevingChallanNo();
            }

            public void put(MNJ_ISSUE_REC_WASH_REC_L_EOImpl obj,
                            Object value) {
                obj.setRecevingChallanNo((String)value);
            }
        }
        ,
        RcvFromWashDate {
            public Object get(MNJ_ISSUE_REC_WASH_REC_L_EOImpl obj) {
                return obj.getRcvFromWashDate();
            }

            public void put(MNJ_ISSUE_REC_WASH_REC_L_EOImpl obj,
                            Object value) {
                obj.setRcvFromWashDate((Date)value);
            }
        }
        ,
        WashRcvQty {
            public Object get(MNJ_ISSUE_REC_WASH_REC_L_EOImpl obj) {
                return obj.getWashRcvQty();
            }

            public void put(MNJ_ISSUE_REC_WASH_REC_L_EOImpl obj,
                            Object value) {
                obj.setWashRcvQty((Number)value);
            }
        }
        ,
        MajorIssues {
            public Object get(MNJ_ISSUE_REC_WASH_REC_L_EOImpl obj) {
                return obj.getMajorIssues();
            }

            public void put(MNJ_ISSUE_REC_WASH_REC_L_EOImpl obj,
                            Object value) {
                obj.setMajorIssues((String)value);
            }
        }
        ,
        ActionTaken {
            public Object get(MNJ_ISSUE_REC_WASH_REC_L_EOImpl obj) {
                return obj.getActionTaken();
            }

            public void put(MNJ_ISSUE_REC_WASH_REC_L_EOImpl obj,
                            Object value) {
                obj.setActionTaken((String)value);
            }
        }
        ,
        CurrectionReqArea {
            public Object get(MNJ_ISSUE_REC_WASH_REC_L_EOImpl obj) {
                return obj.getCurrectionReqArea();
            }

            public void put(MNJ_ISSUE_REC_WASH_REC_L_EOImpl obj,
                            Object value) {
                obj.setCurrectionReqArea((String)value);
            }
        }
        ,
        Remarks {
            public Object get(MNJ_ISSUE_REC_WASH_REC_L_EOImpl obj) {
                return obj.getRemarks();
            }

            public void put(MNJ_ISSUE_REC_WASH_REC_L_EOImpl obj,
                            Object value) {
                obj.setRemarks((String)value);
            }
        }
        ,
        Attribute1 {
            public Object get(MNJ_ISSUE_REC_WASH_REC_L_EOImpl obj) {
                return obj.getAttribute1();
            }

            public void put(MNJ_ISSUE_REC_WASH_REC_L_EOImpl obj,
                            Object value) {
                obj.setAttribute1((String)value);
            }
        }
        ,
        Attribute2 {
            public Object get(MNJ_ISSUE_REC_WASH_REC_L_EOImpl obj) {
                return obj.getAttribute2();
            }

            public void put(MNJ_ISSUE_REC_WASH_REC_L_EOImpl obj,
                            Object value) {
                obj.setAttribute2((String)value);
            }
        }
        ,
        Attribute3 {
            public Object get(MNJ_ISSUE_REC_WASH_REC_L_EOImpl obj) {
                return obj.getAttribute3();
            }

            public void put(MNJ_ISSUE_REC_WASH_REC_L_EOImpl obj,
                            Object value) {
                obj.setAttribute3((String)value);
            }
        }
        ,
        Attribute4 {
            public Object get(MNJ_ISSUE_REC_WASH_REC_L_EOImpl obj) {
                return obj.getAttribute4();
            }

            public void put(MNJ_ISSUE_REC_WASH_REC_L_EOImpl obj,
                            Object value) {
                obj.setAttribute4((String)value);
            }
        }
        ,
        Attribute5 {
            public Object get(MNJ_ISSUE_REC_WASH_REC_L_EOImpl obj) {
                return obj.getAttribute5();
            }

            public void put(MNJ_ISSUE_REC_WASH_REC_L_EOImpl obj,
                            Object value) {
                obj.setAttribute5((String)value);
            }
        }
        ,
        Attribute6 {
            public Object get(MNJ_ISSUE_REC_WASH_REC_L_EOImpl obj) {
                return obj.getAttribute6();
            }

            public void put(MNJ_ISSUE_REC_WASH_REC_L_EOImpl obj,
                            Object value) {
                obj.setAttribute6((String)value);
            }
        }
        ,
        Attribute7 {
            public Object get(MNJ_ISSUE_REC_WASH_REC_L_EOImpl obj) {
                return obj.getAttribute7();
            }

            public void put(MNJ_ISSUE_REC_WASH_REC_L_EOImpl obj,
                            Object value) {
                obj.setAttribute7((String)value);
            }
        }
        ,
        Attribute8 {
            public Object get(MNJ_ISSUE_REC_WASH_REC_L_EOImpl obj) {
                return obj.getAttribute8();
            }

            public void put(MNJ_ISSUE_REC_WASH_REC_L_EOImpl obj,
                            Object value) {
                obj.setAttribute8((String)value);
            }
        }
        ,
        Attribute9 {
            public Object get(MNJ_ISSUE_REC_WASH_REC_L_EOImpl obj) {
                return obj.getAttribute9();
            }

            public void put(MNJ_ISSUE_REC_WASH_REC_L_EOImpl obj,
                            Object value) {
                obj.setAttribute9((String)value);
            }
        }
        ,
        Attribute10 {
            public Object get(MNJ_ISSUE_REC_WASH_REC_L_EOImpl obj) {
                return obj.getAttribute10();
            }

            public void put(MNJ_ISSUE_REC_WASH_REC_L_EOImpl obj,
                            Object value) {
                obj.setAttribute10((String)value);
            }
        }
        ,
        Attribute11 {
            public Object get(MNJ_ISSUE_REC_WASH_REC_L_EOImpl obj) {
                return obj.getAttribute11();
            }

            public void put(MNJ_ISSUE_REC_WASH_REC_L_EOImpl obj,
                            Object value) {
                obj.setAttribute11((String)value);
            }
        }
        ,
        Attribute12 {
            public Object get(MNJ_ISSUE_REC_WASH_REC_L_EOImpl obj) {
                return obj.getAttribute12();
            }

            public void put(MNJ_ISSUE_REC_WASH_REC_L_EOImpl obj,
                            Object value) {
                obj.setAttribute12((String)value);
            }
        }
        ,
        Attribute13 {
            public Object get(MNJ_ISSUE_REC_WASH_REC_L_EOImpl obj) {
                return obj.getAttribute13();
            }

            public void put(MNJ_ISSUE_REC_WASH_REC_L_EOImpl obj,
                            Object value) {
                obj.setAttribute13((String)value);
            }
        }
        ,
        Attribute14 {
            public Object get(MNJ_ISSUE_REC_WASH_REC_L_EOImpl obj) {
                return obj.getAttribute14();
            }

            public void put(MNJ_ISSUE_REC_WASH_REC_L_EOImpl obj,
                            Object value) {
                obj.setAttribute14((String)value);
            }
        }
        ,
        Attribute15 {
            public Object get(MNJ_ISSUE_REC_WASH_REC_L_EOImpl obj) {
                return obj.getAttribute15();
            }

            public void put(MNJ_ISSUE_REC_WASH_REC_L_EOImpl obj,
                            Object value) {
                obj.setAttribute15((String)value);
            }
        }
        ,
        SalesorderId {
            public Object get(MNJ_ISSUE_REC_WASH_REC_L_EOImpl obj) {
                return obj.getSalesorderId();
            }

            public void put(MNJ_ISSUE_REC_WASH_REC_L_EOImpl obj,
                            Object value) {
                obj.setSalesorderId((Number)value);
            }
        }
        ,
        LastUpdateDate {
            public Object get(MNJ_ISSUE_REC_WASH_REC_L_EOImpl obj) {
                return obj.getLastUpdateDate();
            }

            public void put(MNJ_ISSUE_REC_WASH_REC_L_EOImpl obj,
                            Object value) {
                obj.setLastUpdateDate((Date)value);
            }
        }
        ,
        LastUpdatedBy {
            public Object get(MNJ_ISSUE_REC_WASH_REC_L_EOImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(MNJ_ISSUE_REC_WASH_REC_L_EOImpl obj,
                            Object value) {
                obj.setLastUpdatedBy((Number)value);
            }
        }
        ,
        CreationDate {
            public Object get(MNJ_ISSUE_REC_WASH_REC_L_EOImpl obj) {
                return obj.getCreationDate();
            }

            public void put(MNJ_ISSUE_REC_WASH_REC_L_EOImpl obj,
                            Object value) {
                obj.setCreationDate((Date)value);
            }
        }
        ,
        CreatedBy {
            public Object get(MNJ_ISSUE_REC_WASH_REC_L_EOImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(MNJ_ISSUE_REC_WASH_REC_L_EOImpl obj,
                            Object value) {
                obj.setCreatedBy((Number)value);
            }
        }
        ,
        OrgId {
            public Object get(MNJ_ISSUE_REC_WASH_REC_L_EOImpl obj) {
                return obj.getOrgId();
            }

            public void put(MNJ_ISSUE_REC_WASH_REC_L_EOImpl obj,
                            Object value) {
                obj.setOrgId((Number)value);
            }
        }
        ,
        RecevingDate {
            public Object get(MNJ_ISSUE_REC_WASH_REC_L_EOImpl obj) {
                return obj.getRecevingDate();
            }

            public void put(MNJ_ISSUE_REC_WASH_REC_L_EOImpl obj,
                            Object value) {
                obj.setRecevingDate((Date)value);
            }
        }
        ,
        WashEmdPrintInv {
            public Object get(MNJ_ISSUE_REC_WASH_REC_L_EOImpl obj) {
                return obj.getWashEmdPrintInv();
            }

            public void put(MNJ_ISSUE_REC_WASH_REC_L_EOImpl obj,
                            Object value) {
                obj.setWashEmdPrintInv((Number)value);
            }
        }
        ,
        WashType {
            public Object get(MNJ_ISSUE_REC_WASH_REC_L_EOImpl obj) {
                return obj.getWashType();
            }

            public void put(MNJ_ISSUE_REC_WASH_REC_L_EOImpl obj,
                            Object value) {
                obj.setWashType((String)value);
            }
        }
        ,
        ProductionType {
            public Object get(MNJ_ISSUE_REC_WASH_REC_L_EOImpl obj) {
                return obj.getProductionType();
            }

            public void put(MNJ_ISSUE_REC_WASH_REC_L_EOImpl obj,
                            Object value) {
                obj.setProductionType((String)value);
            }
        }
        ,
        WashEmdPrintInvorg {
            public Object get(MNJ_ISSUE_REC_WASH_REC_L_EOImpl obj) {
                return obj.getWashEmdPrintInvorg();
            }

            public void put(MNJ_ISSUE_REC_WASH_REC_L_EOImpl obj,
                            Object value) {
                obj.setWashEmdPrintInvorg((String)value);
            }
        }
        ,
        BpoId {
            public Object get(MNJ_ISSUE_REC_WASH_REC_L_EOImpl obj) {
                return obj.getBpoId();
            }

            public void put(MNJ_ISSUE_REC_WASH_REC_L_EOImpl obj,
                            Object value) {
                obj.setBpoId((Number)value);
            }
        }
        ,
        HeaderEO {
            public Object get(MNJ_ISSUE_REC_WASH_REC_L_EOImpl obj) {
                return obj.getHeaderEO();
            }

            public void put(MNJ_ISSUE_REC_WASH_REC_L_EOImpl obj,
                            Object value) {
                obj.setHeaderEO((HeaderEOImpl)value);
            }
        }
        ,
        MNJ_ISSUEREC_WASH_REC_SIZE_EO {
            public Object get(MNJ_ISSUE_REC_WASH_REC_L_EOImpl obj) {
                return obj.getMNJ_ISSUEREC_WASH_REC_SIZE_EO();
            }

            public void put(MNJ_ISSUE_REC_WASH_REC_L_EOImpl obj,
                            Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(MNJ_ISSUE_REC_WASH_REC_L_EOImpl object);

        public abstract void put(MNJ_ISSUE_REC_WASH_REC_L_EOImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() +
                AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int HEADERID = AttributesEnum.HeaderId.index();
    public static final int LINEID = AttributesEnum.LineId.index();
    public static final int RECEVINGCHALLANNO = AttributesEnum.RecevingChallanNo.index();
    public static final int RCVFROMWASHDATE = AttributesEnum.RcvFromWashDate.index();
    public static final int WASHRCVQTY = AttributesEnum.WashRcvQty.index();
    public static final int MAJORISSUES = AttributesEnum.MajorIssues.index();
    public static final int ACTIONTAKEN = AttributesEnum.ActionTaken.index();
    public static final int CURRECTIONREQAREA = AttributesEnum.CurrectionReqArea.index();
    public static final int REMARKS = AttributesEnum.Remarks.index();
    public static final int ATTRIBUTE1 = AttributesEnum.Attribute1.index();
    public static final int ATTRIBUTE2 = AttributesEnum.Attribute2.index();
    public static final int ATTRIBUTE3 = AttributesEnum.Attribute3.index();
    public static final int ATTRIBUTE4 = AttributesEnum.Attribute4.index();
    public static final int ATTRIBUTE5 = AttributesEnum.Attribute5.index();
    public static final int ATTRIBUTE6 = AttributesEnum.Attribute6.index();
    public static final int ATTRIBUTE7 = AttributesEnum.Attribute7.index();
    public static final int ATTRIBUTE8 = AttributesEnum.Attribute8.index();
    public static final int ATTRIBUTE9 = AttributesEnum.Attribute9.index();
    public static final int ATTRIBUTE10 = AttributesEnum.Attribute10.index();
    public static final int ATTRIBUTE11 = AttributesEnum.Attribute11.index();
    public static final int ATTRIBUTE12 = AttributesEnum.Attribute12.index();
    public static final int ATTRIBUTE13 = AttributesEnum.Attribute13.index();
    public static final int ATTRIBUTE14 = AttributesEnum.Attribute14.index();
    public static final int ATTRIBUTE15 = AttributesEnum.Attribute15.index();
    public static final int SALESORDERID = AttributesEnum.SalesorderId.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int ORGID = AttributesEnum.OrgId.index();
    public static final int RECEVINGDATE = AttributesEnum.RecevingDate.index();
    public static final int WASHEMDPRINTINV = AttributesEnum.WashEmdPrintInv.index();
    public static final int WASHTYPE = AttributesEnum.WashType.index();
    public static final int PRODUCTIONTYPE = AttributesEnum.ProductionType.index();
    public static final int WASHEMDPRINTINVORG = AttributesEnum.WashEmdPrintInvorg.index();
    public static final int BPOID = AttributesEnum.BpoId.index();
    public static final int HEADEREO = AttributesEnum.HeaderEO.index();
    public static final int MNJ_ISSUEREC_WASH_REC_SIZE_EO = AttributesEnum.MNJ_ISSUEREC_WASH_REC_SIZE_EO.index();

    /**
     * This is the default constructor (do not remove).
     */
    public MNJ_ISSUE_REC_WASH_REC_L_EOImpl() {
    }


    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = EntityDefImpl.findDefObject("mnj.mfg.model.entities.MNJ_ISSUE_REC_WASH_REC_L_EO");
        }
        return mDefinitionObject;
    }

    /**
     * Gets the attribute value for HeaderId, using the alias name HeaderId.
     * @return the HeaderId
     */
    public Number getHeaderId() {
        return (Number)getAttributeInternal(HEADERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for HeaderId.
     * @param value value to set the HeaderId
     */
    public void setHeaderId(Number value) {
        setAttributeInternal(HEADERID, value);
    }

    /**
     * Gets the attribute value for LineId, using the alias name LineId.
     * @return the LineId
     */
    public Number getLineId() {
        return (Number)getAttributeInternal(LINEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for LineId.
     * @param value value to set the LineId
     */
    public void setLineId(Number value) {
        setAttributeInternal(LINEID, value);
    }

    /**
     * Gets the attribute value for RecevingChallanNo, using the alias name RecevingChallanNo.
     * @return the RecevingChallanNo
     */
    public String getRecevingChallanNo() {
        return (String)getAttributeInternal(RECEVINGCHALLANNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for RecevingChallanNo.
     * @param value value to set the RecevingChallanNo
     */
    public void setRecevingChallanNo(String value) {
        setAttributeInternal(RECEVINGCHALLANNO, value);
    }

    /**
     * Gets the attribute value for RcvFromWashDate, using the alias name RcvFromWashDate.
     * @return the RcvFromWashDate
     */
    public Date getRcvFromWashDate() {
        return (Date)getAttributeInternal(RCVFROMWASHDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for RcvFromWashDate.
     * @param value value to set the RcvFromWashDate
     */
    public void setRcvFromWashDate(Date value) {
        setAttributeInternal(RCVFROMWASHDATE, value);
    }

    /**
     * Gets the attribute value for WashRcvQty, using the alias name WashRcvQty.
     * @return the WashRcvQty
     */
    public Number getWashRcvQty() {
        return (Number)getAttributeInternal(WASHRCVQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for WashRcvQty.
     * @param value value to set the WashRcvQty
     */
    public void setWashRcvQty(Number value) {
        setAttributeInternal(WASHRCVQTY, value);
    }

    /**
     * Gets the attribute value for MajorIssues, using the alias name MajorIssues.
     * @return the MajorIssues
     */
    public String getMajorIssues() {
        return (String)getAttributeInternal(MAJORISSUES);
    }

    /**
     * Sets <code>value</code> as the attribute value for MajorIssues.
     * @param value value to set the MajorIssues
     */
    public void setMajorIssues(String value) {
        setAttributeInternal(MAJORISSUES, value);
    }

    /**
     * Gets the attribute value for ActionTaken, using the alias name ActionTaken.
     * @return the ActionTaken
     */
    public String getActionTaken() {
        return (String)getAttributeInternal(ACTIONTAKEN);
    }

    /**
     * Sets <code>value</code> as the attribute value for ActionTaken.
     * @param value value to set the ActionTaken
     */
    public void setActionTaken(String value) {
        setAttributeInternal(ACTIONTAKEN, value);
    }

    /**
     * Gets the attribute value for CurrectionReqArea, using the alias name CurrectionReqArea.
     * @return the CurrectionReqArea
     */
    public String getCurrectionReqArea() {
        return (String)getAttributeInternal(CURRECTIONREQAREA);
    }

    /**
     * Sets <code>value</code> as the attribute value for CurrectionReqArea.
     * @param value value to set the CurrectionReqArea
     */
    public void setCurrectionReqArea(String value) {
        setAttributeInternal(CURRECTIONREQAREA, value);
    }

    /**
     * Gets the attribute value for Remarks, using the alias name Remarks.
     * @return the Remarks
     */
    public String getRemarks() {
        return (String)getAttributeInternal(REMARKS);
    }

    /**
     * Sets <code>value</code> as the attribute value for Remarks.
     * @param value value to set the Remarks
     */
    public void setRemarks(String value) {
        setAttributeInternal(REMARKS, value);
    }

    /**
     * Gets the attribute value for Attribute1, using the alias name Attribute1.
     * @return the Attribute1
     */
    public String getAttribute1() {
        return (String)getAttributeInternal(ATTRIBUTE1);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute1.
     * @param value value to set the Attribute1
     */
    public void setAttribute1(String value) {
        setAttributeInternal(ATTRIBUTE1, value);
    }

    /**
     * Gets the attribute value for Attribute2, using the alias name Attribute2.
     * @return the Attribute2
     */
    public String getAttribute2() {
        return (String)getAttributeInternal(ATTRIBUTE2);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute2.
     * @param value value to set the Attribute2
     */
    public void setAttribute2(String value) {
        setAttributeInternal(ATTRIBUTE2, value);
    }

    /**
     * Gets the attribute value for Attribute3, using the alias name Attribute3.
     * @return the Attribute3
     */
    public String getAttribute3() {
        return (String)getAttributeInternal(ATTRIBUTE3);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute3.
     * @param value value to set the Attribute3
     */
    public void setAttribute3(String value) {
        setAttributeInternal(ATTRIBUTE3, value);
    }

    /**
     * Gets the attribute value for Attribute4, using the alias name Attribute4.
     * @return the Attribute4
     */
    public String getAttribute4() {
        return (String)getAttributeInternal(ATTRIBUTE4);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute4.
     * @param value value to set the Attribute4
     */
    public void setAttribute4(String value) {
        setAttributeInternal(ATTRIBUTE4, value);
    }

    /**
     * Gets the attribute value for Attribute5, using the alias name Attribute5.
     * @return the Attribute5
     */
    public String getAttribute5() {
        return (String)getAttributeInternal(ATTRIBUTE5);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute5.
     * @param value value to set the Attribute5
     */
    public void setAttribute5(String value) {
        setAttributeInternal(ATTRIBUTE5, value);
    }

    /**
     * Gets the attribute value for Attribute6, using the alias name Attribute6.
     * @return the Attribute6
     */
    public String getAttribute6() {
        return (String)getAttributeInternal(ATTRIBUTE6);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute6.
     * @param value value to set the Attribute6
     */
    public void setAttribute6(String value) {
        setAttributeInternal(ATTRIBUTE6, value);
    }

    /**
     * Gets the attribute value for Attribute7, using the alias name Attribute7.
     * @return the Attribute7
     */
    public String getAttribute7() {
        return (String)getAttributeInternal(ATTRIBUTE7);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute7.
     * @param value value to set the Attribute7
     */
    public void setAttribute7(String value) {
        setAttributeInternal(ATTRIBUTE7, value);
    }

    /**
     * Gets the attribute value for Attribute8, using the alias name Attribute8.
     * @return the Attribute8
     */
    public String getAttribute8() {
        return (String)getAttributeInternal(ATTRIBUTE8);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute8.
     * @param value value to set the Attribute8
     */
    public void setAttribute8(String value) {
        setAttributeInternal(ATTRIBUTE8, value);
    }

    /**
     * Gets the attribute value for Attribute9, using the alias name Attribute9.
     * @return the Attribute9
     */
    public String getAttribute9() {
        return (String)getAttributeInternal(ATTRIBUTE9);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute9.
     * @param value value to set the Attribute9
     */
    public void setAttribute9(String value) {
        setAttributeInternal(ATTRIBUTE9, value);
    }

    /**
     * Gets the attribute value for Attribute10, using the alias name Attribute10.
     * @return the Attribute10
     */
    public String getAttribute10() {
        return (String)getAttributeInternal(ATTRIBUTE10);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute10.
     * @param value value to set the Attribute10
     */
    public void setAttribute10(String value) {
        setAttributeInternal(ATTRIBUTE10, value);
    }

    /**
     * Gets the attribute value for Attribute11, using the alias name Attribute11.
     * @return the Attribute11
     */
    public String getAttribute11() {
        return (String)getAttributeInternal(ATTRIBUTE11);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute11.
     * @param value value to set the Attribute11
     */
    public void setAttribute11(String value) {
        setAttributeInternal(ATTRIBUTE11, value);
    }

    /**
     * Gets the attribute value for Attribute12, using the alias name Attribute12.
     * @return the Attribute12
     */
    public String getAttribute12() {
        return (String)getAttributeInternal(ATTRIBUTE12);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute12.
     * @param value value to set the Attribute12
     */
    public void setAttribute12(String value) {
        setAttributeInternal(ATTRIBUTE12, value);
    }

    /**
     * Gets the attribute value for Attribute13, using the alias name Attribute13.
     * @return the Attribute13
     */
    public String getAttribute13() {
        return (String)getAttributeInternal(ATTRIBUTE13);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute13.
     * @param value value to set the Attribute13
     */
    public void setAttribute13(String value) {
        setAttributeInternal(ATTRIBUTE13, value);
    }

    /**
     * Gets the attribute value for Attribute14, using the alias name Attribute14.
     * @return the Attribute14
     */
    public String getAttribute14() {
        return (String)getAttributeInternal(ATTRIBUTE14);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute14.
     * @param value value to set the Attribute14
     */
    public void setAttribute14(String value) {
        setAttributeInternal(ATTRIBUTE14, value);
    }

    /**
     * Gets the attribute value for Attribute15, using the alias name Attribute15.
     * @return the Attribute15
     */
    public String getAttribute15() {
        return (String)getAttributeInternal(ATTRIBUTE15);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute15.
     * @param value value to set the Attribute15
     */
    public void setAttribute15(String value) {
        setAttributeInternal(ATTRIBUTE15, value);
    }

    /**
     * Gets the attribute value for SalesorderId, using the alias name SalesorderId.
     * @return the SalesorderId
     */
    public Number getSalesorderId() {
        return (Number)getAttributeInternal(SALESORDERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for SalesorderId.
     * @param value value to set the SalesorderId
     */
    public void setSalesorderId(Number value) {
        setAttributeInternal(SALESORDERID, value);
    }

    /**
     * Gets the attribute value for LastUpdateDate, using the alias name LastUpdateDate.
     * @return the LastUpdateDate
     */
    public Date getLastUpdateDate() {
        return (Date)getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdateDate.
     * @param value value to set the LastUpdateDate
     */
    public void setLastUpdateDate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**
     * Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy.
     * @return the LastUpdatedBy
     */
    public Number getLastUpdatedBy() {
        return (Number)getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdatedBy.
     * @param value value to set the LastUpdatedBy
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for CreationDate, using the alias name CreationDate.
     * @return the CreationDate
     */
    public Date getCreationDate() {
        return (Date)getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreationDate.
     * @param value value to set the CreationDate
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the CreatedBy
     */
    public Number getCreatedBy() {
        return (Number)getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for OrgId, using the alias name OrgId.
     * @return the OrgId
     */
    public Number getOrgId() {
        return (Number)getAttributeInternal(ORGID);
    }

    /**
     * Sets <code>value</code> as the attribute value for OrgId.
     * @param value value to set the OrgId
     */
    public void setOrgId(Number value) {
        setAttributeInternal(ORGID, value);
    }

    /**
     * Gets the attribute value for RecevingDate, using the alias name RecevingDate.
     * @return the RecevingDate
     */
    public Date getRecevingDate() {
        return (Date)getAttributeInternal(RECEVINGDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for RecevingDate.
     * @param value value to set the RecevingDate
     */
    public void setRecevingDate(Date value) {
        setAttributeInternal(RECEVINGDATE, value);
    }

    /**
     * Gets the attribute value for WashEmdPrintInv, using the alias name WashEmdPrintInv.
     * @return the WashEmdPrintInv
     */
    public Number getWashEmdPrintInv() {
        return (Number)getAttributeInternal(WASHEMDPRINTINV);
    }

    /**
     * Sets <code>value</code> as the attribute value for WashEmdPrintInv.
     * @param value value to set the WashEmdPrintInv
     */
    public void setWashEmdPrintInv(Number value) {
        setAttributeInternal(WASHEMDPRINTINV, value);
    }

    /**
     * Gets the attribute value for WashType, using the alias name WashType.
     * @return the WashType
     */
    public String getWashType() {
        return (String)getAttributeInternal(WASHTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for WashType.
     * @param value value to set the WashType
     */
    public void setWashType(String value) {
        setAttributeInternal(WASHTYPE, value);
    }

    /**
     * Gets the attribute value for ProductionType, using the alias name ProductionType.
     * @return the ProductionType
     */
    public String getProductionType() {
        return (String)getAttributeInternal(PRODUCTIONTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ProductionType.
     * @param value value to set the ProductionType
     */
    public void setProductionType(String value) {
        setAttributeInternal(PRODUCTIONTYPE, value);
    }

    /**
     * Gets the attribute value for WashEmdPrintInvorg, using the alias name WashEmdPrintInvorg.
     * @return the WashEmdPrintInvorg
     */
    public String getWashEmdPrintInvorg() {
        return (String)getAttributeInternal(WASHEMDPRINTINVORG);
    }

    /**
     * Sets <code>value</code> as the attribute value for WashEmdPrintInvorg.
     * @param value value to set the WashEmdPrintInvorg
     */
    public void setWashEmdPrintInvorg(String value) {
        setAttributeInternal(WASHEMDPRINTINVORG, value);
    }

    /**
     * Gets the attribute value for BpoId, using the alias name BpoId.
     * @return the BpoId
     */
    public Number getBpoId() {
        return (Number)getAttributeInternal(BPOID);
    }

    /**
     * Sets <code>value</code> as the attribute value for BpoId.
     * @param value value to set the BpoId
     */
    public void setBpoId(Number value) {
        setAttributeInternal(BPOID, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }

    /**
     * @return the associated entity HeaderEOImpl.
     */
    public HeaderEOImpl getHeaderEO() {
        return (HeaderEOImpl)getAttributeInternal(HEADEREO);
    }

    /**
     * Sets <code>value</code> as the associated entity HeaderEOImpl.
     */
    public void setHeaderEO(HeaderEOImpl value) {
        setAttributeInternal(HEADEREO, value);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getMNJ_ISSUEREC_WASH_REC_SIZE_EO() {
        return (RowIterator)getAttributeInternal(MNJ_ISSUEREC_WASH_REC_SIZE_EO);
    }


    /**
     * @param lineId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Number lineId) {
        return new Key(new Object[]{lineId});
    }

    protected void create(AttributeList attributeList) {
        super.create(attributeList);
        oracle.jbo.server.SequenceImpl s =
            new oracle.jbo.server.SequenceImpl("MNJ_ISSUE_REC_WASH_REC_L_S",
                                               getDBTransaction());
        oracle.jbo.domain.Number sVal = s.getSequenceNumber();
        setLineId(sVal);
    }


    protected void doDML(int operation, TransactionEvent e) {

        Map sessionScope = ADFContext.getCurrent().getSessionScope();
        String user = (String)sessionScope.get("userId");
        String orgId = (String)sessionScope.get("orgId");
        System.out.println("Org Name is .... " + orgId);
        String unitName = (String)sessionScope.get("unitName");


        if (operation == DML_INSERT) {


            try {
                // setDivisionId(orgId);
                setWashEmdPrintInv(new oracle.jbo.domain.Number(orgId));
                setCreationDate((Date)Date.getCurrentDate());
                setCreatedBy(new oracle.jbo.domain.Number(user));
                setWashEmdPrintInvorg(unitName);

            } catch (SQLException f) {
                ;
            }
        } else if (DML_UPDATE == operation) {
            try {
                setLastUpdateDate((Date)Date.getCurrentDate());
                setLastUpdatedBy(new oracle.jbo.domain.Number(user));
            } catch (SQLException f) {
                ;
            }
        }

        super.doDML(operation, e);

    }


}
